### ISSUE TITLE
Concurrent streaming of request and response

### ISSUE THREAD

**Issue by Tronic** [encode/httpx#877] opened 2020-03-26 13:17 UTC
Is it possible to send request body and receive response body at the same time?

```python
async with client.stream(..., data=agen()) as response:
    # gets here only once agen() finishes
```
... so I cannot receive anything until once the request is completely sent.

I want to do something like:
```python
async with client.stream(...) as stream:
    async for text in stream.aiter_lines():
        await stream.asend(b"I got " + text.encode())
```

**Comment by tomchristie** [comment] 2020-03-26 13:43
Nope, that's not supported. Like most HTTP clients we always send all the request to completion, and then start reading the response.

We *could* perform both concurrently, but it adds a bunch of complexity, and the trade-off that introduces isn't worth it for us at the moment.

**Comment by Tronic** [comment] 2020-03-26 13:50
Clients such as `curl` and browsers' `fetch` API actually do support it, as do many HTTP servers (I specifically need this in tests of Sanic server, which are based on httpx).

**Comment by tomchristie** [comment] 2020-03-26 14:18
> I specifically need this in tests of Sanic server

You might want to double check, since I think the ASGI dispatcher would handle this, even if the over-the-wire HTTP/1.1 dispatcher doesn't.

**Comment by Tronic** [comment] 2020-03-26 14:35
For now this is solved by speaking HTTP by hand. I'll have a closer look if we need more tests. Thanks!

**Comment by florimondmanca** [comment] 2020-03-27 09:22
#878 seems to be related to this…

I can confirm `curl` is able to read early responses, and doesn't just follow the "serially send request/receive response" flow we're using:

```python
with open("file.txt", "wb") as f:
    for _ in range(100):
        f.write(1000 * b"x" + b"\n")
```

```python
from typing import Callable

import uvicorn
from starlette.requests import Request
from starlette.responses import PlainTextResponse

async def app(scope: dict, receive: Callable, send: Callable) -> None:
    request = Request(scope, receive=receive)
    size = 0
    async for chunk in request.stream():
        size += len(chunk)
        if size > 1000:
            response = PlainTextResponse("Too large", status_code=413)
            await response(scope, receive, send)
            break

uvicorn.run(app, log_level="trace")
```

```console
$ curl -v localhost:8000 -d "@file.txt" -i --trace out.log
== Info: Rebuilt URL to: localhost:8000/
== Info:   Trying 127.0.0.1...
== Info: TCP_NODELAY set
== Info: Connected to localhost (127.0.0.1) port 8000 (#0)
=> Send header, 174 bytes (0xae)
0000: 50 4f 53 54 20 2f 20 48 54 54 50 2f 31 2e 31 0d POST / HTTP/1.1.
0010: 0a 48 6f 73 74 3a 20 6c 6f 63 61 6c 68 6f 73 74 .Host: localhost
0020: 3a 38 30 30 30 0d 0a 55 73 65 72 2d 41 67 65 6e :8000..User-Agen
0030: 74 3a 20 63 75 72 6c 2f 37 2e 35 34 2e 30 0d 0a t: curl/7.54.0..
0040: 41 63 63 65 70 74 3a 20 2a 2f 2a 0d 0a 43 6f 6e Accept: */*..Con
0050: 74 65 6e 74 2d 4c 65 6e 67 74 68 3a 20 31 30 30 tent-Length: 100
0060: 30 30 30 0d 0a 43 6f 6e 74 65 6e 74 2d 54 79 70 000..Content-Typ
0070: 65 3a 20 61 70 70 6c 69 63 61 74 69 6f 6e 2f 78 e: application/x
0080: 2d 77 77 77 2d 66 6f 72 6d 2d 75 72 6c 65 6e 63 -www-form-urlenc
0090: 6f 64 65 64 0d 0a 45 78 70 65 63 74 3a 20 31 30 oded..Expect: 10
00a0: 30 2d 63 6f 6e 74 69 6e 75 65 0d 0a 0d 0a       0-continue....
<= Recv header, 23 bytes (0x17)
0000: 48 54 54 50 2f 31 2e 31 20 31 30 30 20 43 6f 6e HTTP/1.1 100 Con
0010: 74 69 6e 75 65 0d 0a                            tinue..
=> Send data, 16384 bytes (0x4000)
0000: 78 78 78 78 78 78 78 78 78 78 78 78 78 78 78 78 xxxxxxxxxxxxxxxx
[...]
<= Recv header, 39 bytes (0x27)
0000: 48 54 54 50 2f 31 2e 31 20 34 31 33 20 52 65 71 HTTP/1.1 413 Req
0010: 75 65 73 74 20 45 6e 74 69 74 79 20 54 6f 6f 20 uest Entity Too 
0020: 4c 61 72 67 65 0d 0a                            Large..
<= Recv header, 37 bytes (0x25)
0000: 64 61 74 65 3a 20 46 72 69 2c 20 32 37 20 4d 61 date: Fri, 27 Ma
0010: 72 20 32 30 32 30 20 30 39 3a 31 36 3a 32 36 20 r 2020 09:16:26 
0020: 47 4d 54 0d 0a                                  GMT..
<= Recv header, 17 bytes (0x11)
0000: 73 65 72 76 65 72 3a 20 75 76 69 63 6f 72 6e 0d server: uvicorn.
0010: 0a                                              .
<= Recv header, 19 bytes (0x13)
0000: 63 6f 6e 74 65 6e 74 2d 6c 65 6e 67 74 68 3a 20 content-length: 
0010: 39 0d 0a                                        9..
<= Recv header, 41 bytes (0x29)
0000: 63 6f 6e 74 65 6e 74 2d 74 79 70 65 3a 20 74 65 content-type: te
0010: 78 74 2f 70 6c 61 69 6e 3b 20 63 68 61 72 73 65 xt/plain; charse
0020: 74 3d 75 74 66 2d 38 0d 0a                      t=utf-8..
== Info: HTTP error before end of send, stop sending
<= Recv header, 2 bytes (0x2)
0000: 0d 0a                                           ..
<= Recv data, 9 bytes (0x9)
0000: 54 6f 6f 20 6c 61 72 67 65                      Too large
== Info: Closing connection 0

```

**Comment by florimondmanca** [comment] 2020-03-27 09:27
Coincidentally, we initially did support concurrent send/read, but ended up simplifying because it was deemed uncessarily complex for most cases. #569

> I think it's very feasible that we might move back to a concurrent read/write in the future, by addressing #565, but at this point in time I think we should opt for the simplest possible case. In any case, this is the same style that urllib3/requests uses, so we're not regressing here.

_Maybe_ it's time we revisit that assumption, and perhaps consider allowing concurrent send/read in the async case?

**Comment by tomchristie** [comment] 2020-03-27 10:20
So my assessment here would be that while we *might* choose to support early data at a future point, it'd likely be a poor trade off for us to make at this point in time.

The additional complexity means we'd be more likely to either be introducing subtle bugs or be pushing back higher priority items. Basically I think it's a really high cost feature vs. the benefits, and should come further down the line. (Our API doesn't preclude us from being able to transparently add support for it at a later date.)

I think that *particularly* true given that `urllib3`/`requests` also doesn't support it.

Having said that, it's *feasible* that there's a special case in https://github.com/encode/httpx/issues/878 - IE. if we get a write error, then suppress that and move on to reading the response. (And only raise if *reading the response* raises an error.) I'm not sure about that. It looks like brittle server behaviour to me, rather than a client issue, but it'd be helpful to better understand how `urlllib3`/`requests` currently handle that case.

**Comment by florimondmanca** [comment] 2020-03-27 16:42
@tomchristie Agreed on the high cost vs small benefits. I think it's good to push back on it for now… Let's close this and continue any remaining discussion re: silencing write errors (which I don't think is a great idea at this point either?) on #878. :-)

**Closed by florimondmanca** 2020-03-27 16:42 UTC
Labels: concurrency, discussion, http/1.1
