### ISSUE TITLE
ERROR: No matching distribution found for hstspreload

### ISSUE THREAD

**Issue by djmrr** [encode/httpx#856] opened 2020-03-09 21:27 UTC
Hey there!

I really dig this library it's super awesome!

I have been running into an issue performing an install with an internal dependency within httpx:
```
ERROR: No matching distribution found for hstspreload
```

While running this:
```
pip3 download \
--implementation cp \
--only-binary=:all: \
--no-cache-dir \
-r src/requirements.txt -d deps
```

And another variation that's been leveraged is:
```
pip3 download \
--only-binary :all: \
--platform manylinux2010_x86_64 \
--use-pep517 \
--python-version 37 \
--implementation cp \
--abi cp37m \
--no-cache-dir \
-r src/requirements.txt -d deps
```

Y'all are stellar!
Thanks for any input / feedback!

**Comment by florimondmanca** [comment] 2020-03-09 21:52
Hi!

The stripped down reproduction case for this seems to be:

```bash
$ pip download --only-binary=:all: hstspreload
ERROR: Could not find a version that satisfies the requirement hstspreload (from versions: none)
ERROR: No matching distribution found for hstspreload
```

At this point I'm assuming [hstspreload](https://github.com/sethmlarson/hstspreload) doesn't ship binary wheels, which might be something to figure out on that project's side…

**Comment by florimondmanca** [comment] 2020-03-09 21:53
> I'm assuming hstspreload doesn't ship binary wheels

Yup, there's no wheel on PyPI: https://pypi.org/project/hstspreload/2020.3.4/#files

**Comment by florimondmanca** [comment] 2020-03-09 21:56
You can use the `--no-binary` to exclude `hstspreload` from deps that shouldn't be downloaded as binaries:

```console
$ pip download --only-binary=:all: --no-binary=hstspreload httpx -d deps
```

I'm able to run this without issues. :-)

Going to close this off for now, feel free to follow up on the `hstspreload` repo if you'd like to bring wheels there.

Thanks!

**Closed by florimondmanca** 2020-03-09 21:56 UTC

**Comment by djmrr** [comment] 2020-03-09 22:01
@florimondmanca  - rad!
thank ya for such a super quick response!
I'll dig into it and may reach out to the maintainers of hstspreload!

**Comment by tomchristie** [comment] 2020-03-10 09:33
Thanks for such a comprehensive but concise report, and for the good vibes! 👍😃
