### ISSUE TITLE
ValueError: filedescriptor out of range in select()

### ISSUE THREAD

**Issue by zhenglilei** [encode/httpx#1379] opened 2020-11-04 01:59 UTC
### Checklist

- [x] The bug is reproducible against the latest release and/or `master`.
- [x] There are no similar issues or pull requests to fix it yet.

### Describe the bug

```
ERROR:grpc._server:Exception calling application: filedescriptor out of range in select()
Traceback (most recent call last):
  File "/ldap_home/lilei.zheng/king-live/tools/../src/kingcrab_server.py", line 66, in get_blacklist
    response = httpx_client.get(req_url, headers=headers, cookies=cookies, timeout=2.0)
  File "/ldap_home/lilei.zheng/.conda/envs/crabs/lib/python3.6/site-packages/httpx/_client.py", line 812, in get
    timeout=timeout,
  File "/ldap_home/lilei.zheng/.conda/envs/crabs/lib/python3.6/site-packages/httpx/_client.py", line 641, in request
    request, auth=auth, allow_redirects=allow_redirects, timeout=timeout,
  File "/ldap_home/lilei.zheng/.conda/envs/crabs/lib/python3.6/site-packages/httpx/_client.py", line 671, in send
    request, auth=auth, timeout=timeout, allow_redirects=allow_redirects,
  File "/ldap_home/lilei.zheng/.conda/envs/crabs/lib/python3.6/site-packages/httpx/_client.py", line 700, in _send_handling_redirects
    request, auth=auth, timeout=timeout, history=history
  File "/ldap_home/lilei.zheng/.conda/envs/crabs/lib/python3.6/site-packages/httpx/_client.py", line 736, in _send_handling_auth
    response = self._send_single_request(request, timeout)
  File "/ldap_home/lilei.zheng/.conda/envs/crabs/lib/python3.6/site-packages/httpx/_client.py", line 770, in _send_single_request
    timeout=timeout.as_dict(),
  File "/ldap_home/lilei.zheng/.conda/envs/crabs/lib/python3.6/site-packages/httpcore/_sync/connection_pool.py", line 165, in request
    connection = self._get_connection_from_pool(origin)
  File "/ldap_home/lilei.zheng/.conda/envs/crabs/lib/python3.6/site-packages/httpcore/_sync/connection_pool.py", line 209, in _get_connection_from_pool
    if connection.is_connection_dropped():
  File "/ldap_home/lilei.zheng/.conda/envs/crabs/lib/python3.6/site-packages/httpcore/_sync/connection.py", line 137, in is_connection_dropped
    return self.connection is not None and self.connection.is_connection_dropped()
  File "/ldap_home/lilei.zheng/.conda/envs/crabs/lib/python3.6/site-packages/httpcore/_sync/http11.py", line 193, in is_connection_dropped
    return self.socket.is_connection_dropped()
  File "/ldap_home/lilei.zheng/.conda/envs/crabs/lib/python3.6/site-packages/httpcore/_backends/sync.py", line 84, in is_connection_dropped
    rready, _wready, _xready = select.select([self.sock], [], [], 0)
ValueError: filedescriptor out of range in select()
```
### Environment

- OS:    Linux
- Python version:     3.6.12
- HTTPX version:    0.14.1
- Async environment: 
- HTTP proxy: 
- Custom certificates: 

### Additional context

It is suggested using select.poll() instead of select.select(),  please refer https://github.com/docker/docker-py/issues/2278

**Comment by florimondmanca** [comment] 2020-11-04 16:42
Hey!

This is very likely a duplicate of https://github.com/encode/httpcore/issues/182.

I'm working on issuing a release of HTTPCore with the fix for ^, will report back and close when done. :-)

**Comment by florimondmanca** [comment] 2020-11-04 16:51
@zhenglilei Will be released via https://github.com/encode/httpcore/pull/231, thanks!

**Closed by florimondmanca** 2020-11-04 16:51 UTC
Labels: duplicate, httpcore
