### ISSUE TITLE
Unexpected AssertionError (httpx 0.9.5)

### ISSUE THREAD

**Issue by iwoloschin** [encode/httpx#689] opened 2019-12-27 22:47 UTC
I'm getting an unexpected `AssertionError` while trying to do a relatively simple `await client.get()` call.  Since the last time this worked I've done two big things, upgraded my project to use Python3.8 (not really important, but the assignment operator is useful for my project) as well as collapsing several httpx clients into a single, package-wide client, that is now being used to make several concurrent, but unrelated requests to the same host (FastAPI/Uvicorn, so no HTTP/2).

I'm not super familiar with the codebase, but at a quick glance it looks like this might be a problem with issuing the concurrent requests?  I can try to throw a lock around the requests to start, though I think that shouldn't really be necessary?

Not sure if it's useful, but the calling code is using uvloop and running on Linux (specifically the python:3.8 Docker container).

```
  File "/opt/venv/lib/python3.8/site-packages/httpx/client.py", line 679, in get
    return await self.request(
  File "/opt/venv/lib/python3.8/site-packages/httpx/client.py", line 259, in request
    response = await self.send(
  File "/opt/venv/lib/python3.8/site-packages/httpx/client.py", line 403, in send
    response = await self.send_handling_redirects(
  File "/opt/venv/lib/python3.8/site-packages/httpx/client.py", line 465, in send_handling_redirects
    response = await self.send_handling_auth(
  File "/opt/venv/lib/python3.8/site-packages/httpx/client.py", line 591, in send_handling_auth
    response = await self.send_single_request(request, timeout, verify, cert)
  File "/opt/venv/lib/python3.8/site-packages/httpx/client.py", line 618, in send_single_request
    response = await dispatcher.send(
  File "/opt/venv/lib/python3.8/site-packages/httpx/dispatch/connection_pool.py", line 147, in send
    connection = await self.acquire_connection(
  File "/opt/venv/lib/python3.8/site-packages/httpx/dispatch/connection_pool.py", line 165, in acquire_connection
    connection = self.pop_connection(origin)
  File "/opt/venv/lib/python3.8/site-packages/httpx/dispatch/connection_pool.py", line 215, in pop_connection
    connection = self.active_connections.pop_by_origin(origin, http2_only=True)
  File "/opt/venv/lib/python3.8/site-packages/httpx/dispatch/connection_pool.py", line 46, in pop_by_origin
    if http2_only and not connection.is_http2:
  File "/opt/venv/lib/python3.8/site-packages/httpx/dispatch/connection.py", line 175, in is_http2
    assert self.open_connection is not None
AssertionError
```

I don't have a minimal example yet, I can try to put one together though if that'd be helpful.

**Comment by florimondmanca** [comment] 2019-12-27 23:15
Hi @iwoloschin!

A minimal reproduction example might be useful, indeed! At first glance it seems like a race condition. The connection pooling logic has several moving parts, so knowing in which cases this error surfaces would definitely be helpful.

Also if you're able to, feel free to share the TRACE output of your program:

```console
$ HTTPX_LOG_LEVEL=trace python myprogram.py
```

**Comment by iwoloschin** [comment] 2019-12-28 00:25
@florimondmanca I keep forgetting about the environmental variables!  I didn't see anything obvious with a quick test.  Let me see if I can whip up a minimal example that's easier to share.

**Comment by iwoloschin** [comment] 2019-12-28 01:22
No luck on making a minimal test here, but I did figure out that it's not only happening on the first connection, sometimes it happens after a minute or so (there's roughly 3 GETs every 10 seconds).  Since it's all HTTP/1.1 is the connection closed after each request?  That'd still leave us open to a race condition here, though I threw a lock around the GET requests and that did not seem to help.

**Comment by florimondmanca** [comment] 2019-12-28 12:39
@iwoloschin Can we access the code somewhere, or is it private? Having at least some code to look at would definitely help with moving this forward.

> Since it's all HTTP/1.1 is the connection closed after each request?

No — the client does use connection pooling on HTTP/1.1 as well. After a request is finished, the connection is moved to a keepalive state, and reused if/when a request to the same origin is made. If that doesn't happen within 5s then the connection gets deleted.

(Makes me think we might want to document the connection pooling algorithm somewhere, sometime. The code is a bit hard to grasp at first; at least being able to point at some prose about the general workflow might be useful.)

This keepalive expiry enhancement was added in 0.9.4. Are you able to reproduce on 0.9.3? Actually, knowing at which point in our releases this bug started occurring would definitely be useful to pinpoint its origin. :-)

**Comment by iwoloschin** [comment] 2019-12-29 13:39
@florimondmanca unfortunately it's probably not something I can share directly, hence trying to come up with some example code.  Also unfortunately, I can't seem to replicate the issue locally on my development machine, it only seems to work on my "production" system (which is just my own lab environment), which is a rather complicated kubernetes & ceph cluster.

Moving back to 0.9.3 does not seem to resolve the issue.  It's easy to roll back to 0.9 releases, I can also do 0.8 releases (but further back is annoying because of the AsyncClient ==> Client change).  I can also try rolling back to Python 3.7.

**Comment by iwoloschin** [comment] 2019-12-29 13:42
Oh, one other thing, rolling back to 0.9.3 seems to fail, but the next request appears to work fine, which in my use case is actually completely fine since I expect & handle errors (but this is obviously still a bug!).  I think, but don't remember 100%, that with 0.9.5 a failure like this would hang any future requests.  If this sounds like a useful datapoint I can retry with 0.9.5 to confirm this behavior.

**Comment by iwoloschin** [comment] 2019-12-30 18:53
The issue was worse at 0.9.5, a failed request would hang/kill the entire task.

I've gone ahead and created separate clients for each task and see no more errors.  This is fine for me, but it's not the way I would intuitively use httpx so I think this should be left open?

**Comment by dmfigol** [comment] 2019-12-30 23:50
@florimondmanca 

I encountered this traceback as well.
My use-case: I have a local server which exposes REST API. I need to do a lot of queries to it. The code looks like this:
```
class GNS3Project:
    def __init__(self, ...):
          self.http_client = httpx.AsyncClient()

   async def provision_router(self, sema, ...):
         async with sema:
             # several sequential HTTP operations: put/post/get, e.g.:
             # await self.http_client.post(url)

async def main():
    gns3_project = GNS3Project(...)
    sema = asyncio.BoundedSemaphore(25)
    tasks = [
        asyncio.create_task(
            gns3_project.provision_router(
                devices[i], template=router_config_template, sema=sema
            )
        )
        for i in range(500, 600)
    ]
    await asyncio.gather(*tasks)
```
I get:
```
  File ".../app/gns3_project.py", line 164, in add_link_to_switch
    response = await self.http_client.post(url, json=link.dump())
  File ".../.venv/lib/python3.7/site-packages/httpx/client.py", line 761, in post
    trust_env=trust_env,
  File ".../.venv/lib/python3.7/site-packages/httpx/client.py", line 268, in request
    timeout=timeout,
  File ".../.venv/lib/python3.7/site-packages/httpx/client.py", line 402, in send
    request, auth=auth, timeout=timeout, allow_redirects=allow_redirects,
  File ".../.venv/lib/python3.7/site-packages/httpx/client.py", line 454, in send_handling_redirects
    request, auth=auth, timeout=timeout,
  File ".../.venv/lib/python3.7/site-packages/httpx/client.py", line 574, in send_handling_auth
    response = await self.send_single_request(request, timeout)
  File ".../.venv/lib/python3.7/site-packages/httpx/client.py", line 596, in send_single_request
    response = await dispatcher.send(request, timeout=timeout)
  File ".../.venv/lib/python3.7/site-packages/httpx/dispatch/connection_pool.py", line 146, in send
    origin=request.url.origin, timeout=timeout
  File ".../.venv/lib/python3.7/site-packages/httpx/dispatch/connection_pool.py", line 161, in acquire_connection
    connection = self.pop_connection(origin)
  File ".../.venv/lib/python3.7/site-packages/httpx/dispatch/connection_pool.py", line 211, in pop_connection
    connection = self.active_connections.pop_by_origin(origin, http2_only=True)
  File ".../.venv/lib/python3.7/site-packages/httpx/dispatch/connection_pool.py", line 47, in pop_by_origin
    if http2_only and not connection.is_http2:
  File ".../.venv/lib/python3.7/site-packages/httpx/dispatch/connection.py", line 159, in is_http2
    assert self.open_connection is not None
```
I've tried increasing connection limits using `AsyncClient(pool_limits=PoolLimits(soft_limit=999, hard_limit=1000)`, but it didn't solve the problem. Also this part is not really documented, I am not sure what soft and hard limits actually do.
I'd greatly appreciate any help on this. I can reproduce this problem in my environment 100%.

**Comment by kshramt** [comment] 2019-12-31 06:22
https://github.com/encode/httpx/pull/698 seems to solve the issue.

Test code:
```
import asyncio
import httpx


def main():
    asyncio.run(run())


async def run():
    async with httpx.Client() as client:
        await asyncio.gather(*[runn(client, 20) for _ in range(20)])


async def runn(client, n):
    for _ in range(n):
        await run1(client)


def run1(client):
    return client.get("https://www.yahoo.com/")


main()
```

**Comment by florimondmanca** [comment] 2019-12-31 09:21
@kshramt It seems you managed to pin the issue down, thanks! Seems to be an issue with adding the connection to `.active_connections` *before* establishing the connection, which sometimes results in the connection store inspecting `.is_http2` on a not-yet-established connection, hence the error.

**Closed** 2019-12-31 13:18 UTC
Labels: bug, pooling
