### ISSUE TITLE
An open stream object is being garbage collected; call "stream.close()" explicitly.

### ISSUE THREAD

**Issue by klen** [encode/httpx#1101] opened 2020-07-30 06:11 UTC
### Checklist

- [x ] The bug is reproducible against the latest release and/or `master`.
- [x ] There are no similar issues or pull requests to fix it yet.

### Describe the bug

In my case, I don't need to read responses body, so I use `AsyncClient.stream` functionality.
Since version 0.13 `httpx` has started to show the warning message: `An open stream object is being garbage collected; call "stream.close()" explicitly.`. 

### To reproduce

```python
import asyncio as aio
import httpx

client = httpx.AsyncClient()
loop = aio.get_event_loop()

async def reproduce():
    async with client.stream('GET', 'https://github.com') as res:
        print('Response:', res.status_code)

loop.run_until_complete(reproduce())

```
**Output:**
```
Response: 200
An open stream object is being garbage collected; call "stream.close()" explicitly.
```

### Expected behavior

No warning messages

### Environment

- OS: MacOS
- Python version: 3.8.0
- HTTPX version: 0.13.3
- Async environment: asyncio

**Comment by florimondmanca** [comment] 2020-07-30 07:28
Hello,

I believe this is a duplicate of #714. See https://github.com/encode/httpx/issues/714#issuecomment-574684839: try upgrading to at least 3.8.1 (latest 3.8 version is 3.8.5) and see if it removes the warning.

Thanks!

**Closed by florimondmanca** 2020-07-30 07:28 UTC
