### ISSUE TITLE
asyncio `resume_reading` bug exposed while streaming response.

### ISSUE THREAD

**Issue by sargun** [encode/httpx#1213] opened 2020-08-22 00:56 UTC
### Checklist

- [X] The bug is reproducible against the latest release and/or `master`. (Release 0.14.1)
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug
When running a large number of async streaming read requests with http/1.1 + SSL, I occasionally get this error:
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/sdhillon/repos/stonks/eodhistorical/equities.py", line 190, in <module>
    update_equities(d.isoformat(), days_after=31)
  File "/Users/sdhillon/repos/stonks/eodhistorical/equities.py", line 163, in update_equities
    rows = asyncio.run(collect_rows(start, end, symbols))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/Users/sdhillon/repos/stonks/eodhistorical/equities.py", line 147, in collect_rows
    symbol_rows = await job
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/tasks.py", line 560, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "/Users/sdhillon/repos/stonks/venv/lib/python3.7/site-packages/tenacity/_asyncio.py", line 43, in call
    do = self.iter(retry_state=retry_state)
  File "/Users/sdhillon/repos/stonks/venv/lib/python3.7/site-packages/tenacity/__init__.py", line 356, in iter
    return fut.result()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/Users/sdhillon/repos/stonks/venv/lib/python3.7/site-packages/tenacity/_asyncio.py", line 46, in call
    result = await fn(*args, **kwargs)
  File "/Users/sdhillon/repos/stonks/eodhistorical/equities.py", line 58, in collect_rows_for_symbol
    async for chunk in resp.aiter_lines():
  File "/Users/sdhillon/repos/stonks/venv/lib/python3.7/site-packages/httpx/_models.py", line 992, in aiter_lines
    async for text in self.aiter_text():
  File "/Users/sdhillon/repos/stonks/venv/lib/python3.7/site-packages/httpx/_models.py", line 986, in aiter_text
    async for chunk in self.aiter_bytes():
  File "/Users/sdhillon/repos/stonks/venv/lib/python3.7/site-packages/httpx/_models.py", line 975, in aiter_bytes
    async for chunk in self.aiter_raw():
  File "/Users/sdhillon/repos/stonks/venv/lib/python3.7/site-packages/httpx/_models.py", line 1008, in aiter_raw
    async for part in self._raw_stream:
  File "/Users/sdhillon/repos/stonks/venv/lib/python3.7/site-packages/httpcore/_async/connection_pool.py", line 50, in __aiter__
    async for chunk in self.stream:
  File "/Users/sdhillon/repos/stonks/venv/lib/python3.7/site-packages/httpcore/_bytestreams.py", line 72, in __aiter__
    async for chunk in self._aiterator:
  File "/Users/sdhillon/repos/stonks/venv/lib/python3.7/site-packages/httpcore/_async/http11.py", line 143, in _receive_response_data
    event = await self._receive_event(timeout)
  File "/Users/sdhillon/repos/stonks/venv/lib/python3.7/site-packages/httpcore/_async/http11.py", line 160, in _receive_event
    data = await self.socket.read(self.READ_NUM_BYTES, timeout)
  File "/Users/sdhillon/repos/stonks/venv/lib/python3.7/site-packages/httpcore/_backends/asyncio.py", line 135, in read
    self.stream_reader.read(n), timeout.get("read")
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/streams.py", line 646, in read
    self._maybe_resume_transport()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/streams.py", line 417, in _maybe_resume_transport
    self._transport.resume_reading()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/sslproto.py", line 345, in resume_reading
    self._ssl_protocol._transport.resume_reading()
AttributeError: 'NoneType' object has no attribute 'resume_reading'
```

### To reproduce
It's non-trivial to reproduce, but this seems to be a "commonly known" bug: https://github.com/falconkirtaran/wpull/commit/0c517bab510ff9555bff055b4e1e78a807e0bd90

### Expected behavior
Throw an httpx level network error

### Actual behavior
Throws not that error.

### Environment

- OS: Mac, Linux
- Python version: 3.7.8
- HTTPX version: 0.14.1
- Async environment: asyncio
- HTTP proxy: No
- Custom certificates: No

### Additional context
https://github.com/falconkirtaran/wpull/commit/0c517bab510ff9555bff055b4e1e78a807e0bd90
Seems to be a long-standing bug with any asyncio users:
https://www.mail-archive.com/python-list@python.org/msg412208.html

**Comment by tomchristie** [comment] 2020-08-24 10:58
Yup looks like an `asyncio` bug that can occur when a stream that is paused for reading becomes closed, and then later raises this error during the `read()` call.

Looks similar to https://bugs.python.org/issue38019 / https://github.com/python/cpython/commit/58498bc7178608b1ab031994ca09c43889ce3e76

Perhaps even resolved by that? (But I don't think so.)

It'd be *really* good to narrow this down into a plain reproducible cases against `asyncio` that we can file as a bug.

We *can* also work around it on our side. Not immediately apparent to me if we should treat the bug occurring as a regular graceful close, and just return `b""` in that case, or if it's an error condition. (And should be raising `ReadError("Connection closed unexpectedly")`)

**Comment by cdeler** [comment] 2020-10-01 14:49
The additional link might be attached to this ticket: https://bugs.python.org/issue36098 

There is a link for this repl:
https://repl.it/@thehesiod/PristineBonyBugs#main.py
Which is a bit outdated, but, having cut of `pool_limits` from the snippet, I successfully reproduced the bug on my machine

I saved the repl to this [gist](https://gist.github.com/cdeler/3b695de71e4c092e6f88772f7d4f4d45)  to not loose it

**Comment by cdeler** [comment] 2020-10-01 17:46
I made another step.

I split the server and the client into dedicated files, then tailored a bit client's code adding a client using `httpcore`.

Here is a new gist: https://gist.github.com/cdeler/f43704721829e6ed3c799ddc7d443d5c

The interesting fact:
`httpcore_client` works without errors, but `httpx_client` still falls with the exception

`httpcore==0.11.0`
`httpx` is `c9354282ba60a857f959e5fe60cdf2b74cdbd294` (`0.15.5` from the repo)

**Comment by tomchristie** [comment] 2020-10-01 18:36
Great work. Really good point for us to narrow it down from. (And to be able to confirm any fix here)

**Comment by cdeler** [comment] 2020-10-01 18:51
@tomchristie 
So if we just masquerade the error by `try`-`except` block, it would provide us with good explained error:
```python
    async def read(self, n: int, timeout: TimeoutDict) -> bytes:
        exc_map = {asyncio.TimeoutError: ReadTimeout, OSError: ReadError}

        try:
            async with self.read_lock:
                with map_exceptions(exc_map):
                    return await asyncio.wait_for(
                        self.stream_reader.read(n), timeout.get("read")
                    )
        except AttributeError:
            return b""
```

Gives
> httpcore.RemoteProtocolError: peer closed connection without sending complete message body (received 917504 bytes, expected 1000000)

**Comment by tomchristie** [comment] 2020-10-01 19:39
Yup that *looks* like a pretty sensible behaviour there.

**Comment by cdeler** [comment] 2020-10-01 20:16
@tomchristie 

I created a PR if you don't mind

**Closed** 2020-10-06 09:52 UTC
Labels: bug, concurrency/asyncio, external
