### ISSUE TITLE
httpx not playing along well with proxy with authentication

### ISSUE THREAD

**Issue by AntonioL** [encode/httpx#847] opened 2020-03-04 21:45 UTC
I am trying to use a NordVPN HTTP Proxy. One needs to supply user and password.

From reading the documentation of httpx it seems to me that the below should work but I am getting error code 407 which means that authentication definitely did not happen.

I can provide more information to troubleshoot if needed. I am not sure what is going on in there and what info would you need for that.

```python
    proxy = httpx.Proxy(
        url=f"http://[username]%40[mail-domain]:[password]@{proxy}:80"
    )

    with httpx.Client(proxies=proxy, trust_env=False) as client:
        resp = client.get("https://www.gazzetta.it")
        print(resp.text)
 ```

**Comment by AntonioL** [comment] 2020-03-04 21:46
Actually it seems similar to this issue:
https://github.com/encode/httpx/pull/780

WIll try updating the httpx library.

**Comment by florimondmanca** [comment] 2020-03-04 21:47
Closing as a duplicate of https://github.com/encode/httpx/issues/779 for now, feel free to reopen if you come across any issues with the latest version of HTTPX. :)

**Comment by AntonioL** [comment] 2020-03-04 21:48
I am using 0.11.1 version of the library.

I suspect that the fix in there did not make into a new package version, right?

**Closed by florimondmanca** 2020-03-04 21:47 UTC
Labels: proxies

**Comment by florimondmanca** [comment] 2020-03-04 21:51
Ah indeed, latest release is from Jan 17 (quite a while back now!), and #780 was merged on Jan 19.

Can you verify this is fixed on `master`? A new release should be coming soon (see #829), although it's a shame we didn't get around to publishing a point release for #780.

**Comment by AntonioL** [comment] 2020-03-04 21:55
Cool! Time to sharpen up my pip voodoo.

Thanks for the advice
