### ISSUE TITLE
comparing the behavior between requests and HTTPX in HTTPS auth proxy usage

### ISSUE THREAD

**Issue by adamzlo** [encode/httpx#1178] opened 2020-08-14 21:42 UTC
As i mentioned on the chat, i have tried to use HTTPS auth proxy to send requests to HTTPS websites, but it does not work. 
```        
proxies = httpx.Proxy(
            url="https://username:password@host:port",
            mode="FORWARD_ONLY",
        )
async with httpx.AsyncClient(proxies=proxies) as client:
      response = await client.get("https://httpbin.org/ip")
      print(response.text)
```
When i try to send this request, i get timeout error all the time, but when i change url in httpx.Proxy() to http one, i can access http websites with changed ip. It seems like my proxy is not supporting connecting via HTTPS, but in requests library it works fine. I have encountered this problem in other libraries that supports async requests and i wonder where the problem is.
```
proxies = httpx.Proxy(
            url="http://username:password@host:port",
            mode="FORWARD_ONLY",
        )
async with httpx.AsyncClient(proxies=proxies) as client:
      response = await client.get("http://httpbin.org/ip")
      print(response.text)
```
After changing request to HTTP, the ip is from the proxy and everything seems to work well, but as you may know not on all sites it works like that.
```
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\Adam\Anaconda3\envs\sizeer\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\Adam\Anaconda3\envs\sizeer\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Adam\Desktop\sizeer\test2.py", line 59, in what
    asyncio.get_event_loop().run_until_complete(new.main())
  File "C:\Users\Adam\Anaconda3\envs\sizeer\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\Adam\Desktop\sizeer\test2.py", line 50, in main
    response = await client.get("https://httpbin.org/ip")
  File "C:\Users\Adam\Anaconda3\envs\sizeer\lib\site-packages\httpx\_client.py", line 1408, in get
    return await self.request(
  File "C:\Users\Adam\Anaconda3\envs\sizeer\lib\site-packages\httpx\_client.py", line 1241, in request
    response = await self.send(
  File "C:\Users\Adam\Anaconda3\envs\sizeer\lib\site-packages\httpx\_client.py", line 1272, in send
    response = await self._send_handling_redirects(
  File "C:\Users\Adam\Anaconda3\envs\sizeer\lib\site-packages\httpx\_client.py", line 1301, in _send_handling_redirects
    response = await self._send_handling_auth(
  File "C:\Users\Adam\Anaconda3\envs\sizeer\lib\site-packages\httpx\_client.py", line 1338, in _send_handling_auth
    response = await self._send_single_request(request, timeout)
  File "C:\Users\Adam\Anaconda3\envs\sizeer\lib\site-packages\httpx\_client.py", line 1363, in _send_single_request
    (
  File "C:\Users\Adam\Anaconda3\envs\sizeer\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\Adam\Anaconda3\envs\sizeer\lib\site-packages\httpx\_exceptions.py", line 359, in map_exceptions
    raise mapped_exc(message, **kwargs) from None  # type: ignore
httpx._exceptions.ConnectTimeout

Process finished with exit code 0

```
That's the error i am getting after using HTTPS request. And below is the usage of https proxy in requests library:
```
s = requests.Session()
proxies = {
      "http": "http://username:password@host:port",
      "https": "https://username:password@host:port"
}
response = s.get("https://httpbin.org/ip", proxies=proxies)
```
I have used the same proxies with requests library and i haven't witnessed any issues when connecting to HTTPS websites.
```
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\Adam\Anaconda3\envs\sizeer\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\Adam\Anaconda3\envs\sizeer\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Adam\Desktop\sizeer\test2.py", line 59, in what
    asyncio.get_event_loop().run_until_complete(new.main())
  File "C:\Users\Adam\Anaconda3\envs\sizeer\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\Adam\Desktop\sizeer\test2.py", line 50, in main
    response = await client.get("https://httpbin.org/ip")
  File "C:\Users\Adam\Anaconda3\envs\sizeer\lib\site-packages\httpx\_client.py", line 1408, in get
    return await self.request(
  File "C:\Users\Adam\Anaconda3\envs\sizeer\lib\site-packages\httpx\_client.py", line 1241, in request
    response = await self.send(
  File "C:\Users\Adam\Anaconda3\envs\sizeer\lib\site-packages\httpx\_client.py", line 1272, in send
    response = await self._send_handling_redirects(
  File "C:\Users\Adam\Anaconda3\envs\sizeer\lib\site-packages\httpx\_client.py", line 1301, in _send_handling_redirects
    response = await self._send_handling_auth(
  File "C:\Users\Adam\Anaconda3\envs\sizeer\lib\site-packages\httpx\_client.py", line 1338, in _send_handling_auth
    response = await self._send_single_request(request, timeout)
  File "C:\Users\Adam\Anaconda3\envs\sizeer\lib\site-packages\httpx\_client.py", line 1363, in _send_single_request
    (
  File "C:\Users\Adam\Anaconda3\envs\sizeer\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\Adam\Anaconda3\envs\sizeer\lib\site-packages\httpx\_exceptions.py", line 359, in map_exceptions
    raise mapped_exc(message, **kwargs) from None  # type: ignore
httpx._exceptions.ConnectError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1108)

Process finished with exit code 0

```
And that's the error i get when using different proxy provider. However both works well in requests library.

**Comment by florimondmanca** [comment] 2020-08-15 07:06
Hey!

So:

- If your proxy is non-HTTPS, the ConnectTimeout when issuing an HTTPS with FORWARD_ONLY is to be expected. In this mode HTTPX will try to connect using HTTPS to the proxy (since that's the requested scheme) and fail to do so since the proxy does not support it.
- It's possible Requests (via urllib3) takes a different approach. Can you confirm what happens if you remove the `https` key from the proxies dict in the Requests example?
- What does curl say?

```bash
# Does this return the proxy IP?
HTTP_PROXY="http://..." curl https://httpbin.org/ip

# Does this succeed?
HTTPS_PROXY="https://..." curl https://httpbin.org/ip
```

**Comment by adamzlo** [comment] 2020-08-15 08:19
After removing https key from the proxies dict in Requests example ip is from the proxy only when i connect via HTTP. However when i use Residential proxies, and using this code
```
# Does this return the proxy IP?
HTTP_PROXY="http://..." curl https://httpbin.org/ip
```
it actually changes the ip. But when i use this 
```
# Does this succeed?
HTTPS_PROXY="https://..." curl https://httpbin.org/ip
``` 
it fails. What's more interesting when i use DC proxies from different provider, i got the same errors as before no mater which code i use.

**Comment by florimondmanca** [comment] 2020-08-15 08:23
@adamzlo I think curl requires using lowercase env vars, eg `http_proxy=...` and `https_proxy=...` (at least when using lowercase HTTP_PROXY curl does not seem to use the proxy at all).

---

@adamzlo Although it's not super clear in your issue description, I _think_ (please confirm) that the unexpected behavior you're seeing is "when using an HTTP proxy, the server sees HTTPS requests with my IP instead of the proxy's IP".

Based on this assumption, I did my own testing against a live proxy and `httpx==0.14.1`. Spoiler: I'm not able to reproduce…

I ran [proxy.py](https://github.com/abhinavsingh/proxy.py) (what a brilliant piece of software!) on my DigitalOcean VM and here's the behavior I saw:

* When using an HTTP proxy (as seems to be your case) the IP is that of the proxy for both HTTP and HTTPS requests.
* When using a properly configured HTTPS proxy, and using `FORWARD_ONLY`, the IP is also that of for both HTTP and HTTPS requests.

Here's my setup:

**HTTP proxy setup**

```bash
proxy --hostname <SERVER_IP> --basic-auth user:pass
```

```python
# client_http.py
import httpx

proxies = "http://user:pass@<SERVER_IP>:8899"

with httpx.Client(proxies=proxies) as client:
    response = client.get("http://httpbin.org/ip")
    print("HTTP:", response.text)

    response = client.get("https://httpbin.org/ip")
    print("HTTPS:", response.text)
```

Output show the server IP (where the proxy runs), not that of my laptop:

```console
HTTP: {
  "origin": "<SERVER_IP>"
}

HTTPS: {
  "origin": "<SERVER_IP>"
}
```

**HTTPS proxy setup**

Dependencies:

```bash
pip install trustme-cli proxy.py
```

Generate certs:

```
trustme-cli -i <SERVER_IP>
```

Transfer server certs to server:

```
scp server.key server.pem <USER>@<SERVER_IP>:/tmp/
```

Launch proxy:

```bash
proxy --hostname <SERVER_IP> --cert-file /tmp/server.pem --key-file /tmp/server.key --basic-auth user:pass
```

Client:

```python
# client_https.py
import httpx

proxies = httpx.Proxy(url="https://user:pass@<SERVER_IP>:8899", mode="FORWARD_ONLY")

with httpx.Client(proxies=proxies, verify="debug/client.pem") as client:
    response = client.get("http://httpbin.org/ip")
    print("HTTP:", response.text)

    response = client.get("https://httpbin.org/ip")
    print("HTTPS:", response.text)

```

Output shows again the server IP, not that of my laptop.

**Comment by florimondmanca** [comment] 2020-08-15 08:30
@adamzlo Can you please _explicitly_ state what is the unexpected behavior here? Are you trying to get the proxy to hide your local IP? Is your server authentication IP-sensitive? It would really help decide whether there's anything wrong (I don't think so - see my testing above), or if we should close this off as "non-reproducible and perhaps a proxy config issue".

In general, please try to be as explicit as you can. For example, what does

>  it fails.

_precisely_ means? What error do you get? Is there a traceback? Etc.

Thanks!

**Comment by adamzlo** [comment] 2020-08-15 08:33
i get this error
```
Traceback (most recent call last):
  File "C:\Users\Adam\Anaconda3\envs\sizeer\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\Adam\Anaconda3\envs\sizeer\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Adam\Desktop\sizeer\test2.py", line 59, in what
    asyncio.get_event_loop().run_until_complete(new.main())
  File "C:\Users\Adam\Anaconda3\envs\sizeer\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\Adam\Desktop\sizeer\test2.py", line 50, in main
    response = await client.get("https://httpbin.org/ip")
  File "C:\Users\Adam\Anaconda3\envs\sizeer\lib\site-packages\httpx\_client.py", line 1408, in get
    return await self.request(
  File "C:\Users\Adam\Anaconda3\envs\sizeer\lib\site-packages\httpx\_client.py", line 1241, in request
    response = await self.send(
  File "C:\Users\Adam\Anaconda3\envs\sizeer\lib\site-packages\httpx\_client.py", line 1272, in send
    response = await self._send_handling_redirects(
  File "C:\Users\Adam\Anaconda3\envs\sizeer\lib\site-packages\httpx\_client.py", line 1301, in _send_handling_redirects
    response = await self._send_handling_auth(
  File "C:\Users\Adam\Anaconda3\envs\sizeer\lib\site-packages\httpx\_client.py", line 1338, in _send_handling_auth
    response = await self._send_single_request(request, timeout)
  File "C:\Users\Adam\Anaconda3\envs\sizeer\lib\site-packages\httpx\_client.py", line 1363, in _send_single_request
    (
  File "C:\Users\Adam\Anaconda3\envs\sizeer\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\Adam\Anaconda3\envs\sizeer\lib\site-packages\httpx\_exceptions.py", line 359, in map_exceptions
    raise mapped_exc(message, **kwargs) from None  # type: ignore
httpx._exceptions.ConnectError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1108)

Process finished with exit code 0
```
when using this code
```
        proxies = httpx.Proxy(
            url="https://username:password@host:port",
            mode="TUNNEL_ONLY",
        )
 

        async with httpx.AsyncClient(proxies=proxies) as client:
            response = await client.get("https://httpbin.org/ip")
            print(response.text)
```
According to the last question, no, i do not confuse the proxy's IP and my home IP.

**Comment by adamzlo** [comment] 2020-08-15 08:38
@florimondmanca  I do not want my home IP to be seen by the website, so i need to be sure that it changes before the request is sent. Now i wonder if that's proxy's fault or my computer.

**Comment by florimondmanca** [comment] 2020-08-15 08:41
>  I do not want my home IP to be seen by the website, so i need to be sure that it changes before the request is sent. Now i wonder if that's proxy's fault or my computer.

Thanks. As you can see from my testing using `proxy.py`, even when using a standard HTTP proxy what I see is that to get the IP changed I only need to use `Client(proxy="http://<PROXY_HOSTNAME")`. So I also wonder if your proxy might not be misconfigured. If you have access to your proxy machine and it has Python, you could try `pip3 install proxy.py` and then `proxy --hostname 0.0.0.0 --basic-auth <USER>:<PASS>`, and see what that does.

For now, I'm going to close this off as non-reproducible. :-)

Thanks!

**Closed by florimondmanca** 2020-08-15 08:41 UTC
Labels: needs confirmation, proxies, requests-compat

**Comment by adamzlo** [comment] 2020-08-16 08:13
@florimondmanca finally i get my proxy working with curl, and it changes the ip no matter if it is HTTP or HTTPS website, so i am now sure that it is not proxy's fault

**Comment by adamzlo** [comment] 2020-08-16 08:52
@florimondmanca What if i wanted to send for example 10 requests at one time, each with different auth proxy to HTTPS website? Do i have to make your HTTPS setup manually every time i want to use new proxy?
