### ISSUE TITLE
verify argument seem unsupported by async client

### ISSUE THREAD

**Issue by mchugh19** [encode/httpx#1028] opened 2020-06-18 10:54 UTC
### Checklist

- [x] The bug is reproducible against the latest release and/or `master`.
- [x] There are no similar issues or pull requests to fix it yet.

### Describe the bug
Get error `TypeError: get() got an unexpected keyword argument 'verify'` when I try to disable ssl validation for a client.get call.

### To reproduce
Our environment uses proxy servers and local ssl certs, so I'd just like to disable ssl validation entirely.
```
async with httpx.AsyncClient() as client:
            r = await client.get(
                "https://someserver", verify=False
            )
```
Returns back
```
...
 File "C:\code\gits\project.py", line 158, in get_support_matrix
    "https://someserver", verify=False
TypeError: get() got an unexpected keyword argument 'verify'
```

### Expected behavior
`verify=False` to function as documented at https://www.python-httpx.org/advanced/

> Or you can also disable the SSL verification entirely, which is not recommended.
import httpx
r = httpx.get("https://example.org", verify=False)

### Actual behavior
TypeError: get() got an unexpected keyword argument 'verify'

### Debugging material
Complete test case for python 3.6:
```
import httpx
import asyncio

async def testfun():
    async with httpx.AsyncClient() as client:
        r = await client.get('https://www.example.org/', verify=False)
    print(r)

loop = asyncio.get_event_loop()
loop.run_until_complete(testfun())
loop.close()
```

### Environment

- OS: Windows
- Python version: Python 3.6.2
- HTTPX version: Version: 0.13.3
- Async environment: asyncio
- HTTP proxy: yes
- Custom certificates: yes

### Additional context

**Comment by florimondmanca** [comment] 2020-06-18 11:46
Hi there,

Not a bug I believe, `verify` is to be passed at the client level: `AsyncClient(verify=...)`. (If the docs say otherwise then that should be fixed.)

There was a decision to remove it from request methods, due to too low complexity vs value ratio. If you need to disable SSL verification on a specific request you can use a throwaway client. I think there are past issues related to this where you’d find more background, but I’m not able to dig back right now. :-)

Cheers!

**Closed** 2020-06-18 11:46 UTC
Labels: question

**Comment by florimondmanca** [comment] 2020-06-18 11:48
Update: here is the relevant docs section which states the same than what I’ve shared here: https://www.python-httpx.org/advanced/#ssl-configuration-on-client-instances

**Comment by sharifulgeo** [comment] 2024-07-07 16:09
> https://www.python-httpx.org/advanced/#ssl-configuration-on-client-instances

404 ----> not found: lik is dead!!

**Comment by NiciSteck** [comment] 2024-07-10 12:22
Since there appears to be a new comment 4 years later anyways I just want to add that in this documentation (https://www.python-httpx.org/api/#asyncclient) the async get method parameters refer to httpx.request (Parameters: See httpx.request.) which lists verify as a parameter. Seems to be a small error in the docs
