### ISSUE TITLE
Trying to use SpooledTemporaryFile in client.put()'s data parameter leads to an error

### ISSUE THREAD

**Issue by masi456** [encode/httpx#837] opened 2020-02-29 21:46 UTC
Hey guys,

I encountered something today and I was wondering if that was by design or a bug?

OS platform: Windows 10 64bit
Python version: 3.8
Installed dependencies and versions (python -m pip freeze): 
```
certifi==2019.11.28
chardet==3.0.4
h11==0.9.0
h2==3.2.0
hpack==3.0.0
hstspreload==2020.2.29
httpx==0.11.1
hyperframe==5.2.0
idna==2.9
rfc3986==1.3.2
sniffio==1.1.0
urllib3==1.25.8
```

Code snippet (minimal reproducable example):
```
import tempfile
import httpx
import asyncio

file = tempfile.SpooledTemporaryFile(mode="rw")
file.write("Hello World")

async def main():
    async with httpx.AsyncClient() as client:
        await client.put("http://localhost:9998/meta", data=file)

asyncio.run(main())
```

Error traceback:
```
Traceback (most recent call last):
  File "c:\Users\xxx\.vscode\extensions\ms-python.python-2020.2.64397\pythonFiles\ptvsd_launcher.py", line 48, in <module>
    main(ptvsdArgs)
  File "c:\Users\xxx\.vscode\extensions\ms-python.python-2020.2.64397\pythonFiles\lib\python\old_ptvsd\ptvsd\__main__.py", line 432, in main
    run()
  File "c:\Users\xxx\.vscode\extensions\ms-python.python-2020.2.64397\pythonFiles\lib\python\old_ptvsd\ptvsd\__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "c:\python38\lib\runpy.py", line 263, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "c:\python38\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "c:\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "d:\xxx\python\bug\main.py", line 12, in <module>
    asyncio.run(main())
  File "c:\python38\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "c:\python38\lib\asyncio\base_events.py", line 612, in run_until_complete
    return future.result()
  File "d:\xxx\python\bug\main.py", line 10, in main
    await client.put("http://localhost:9998/meta", data=file)
  File "D:\xxx\python\bug\venv\lib\site-packages\httpx\client.py", line 1333, in put
    return await self.request(
  File "D:\xxx\python\bug\venv\lib\site-packages\httpx\client.py", line 1096, in request
    response = await self.send(
  File "D:\xxx\python\bug\venv\lib\site-packages\httpx\client.py", line 1117, in send
    response = await self.send_handling_redirects(
  File "D:\xxx\python\bug\venv\lib\site-packages\httpx\client.py", line 1147, in send_handling_redirects
    response = await self.send_handling_auth(
  File "D:\xxx\python\bug\venv\lib\site-packages\httpx\client.py", line 1184, in send_handling_auth
    response = await self.send_single_request(request, timeout)
  File "D:\xxx\python\bug\venv\lib\site-packages\httpx\client.py", line 1208, in send_single_request
    response = await dispatcher.send(request, timeout=timeout)
  File "D:\xxx\python\bug\venv\lib\site-packages\httpx\dispatch\connection_pool.py", line 157, in send
    raise exc
  File "D:\xxx\python\bug\venv\lib\site-packages\httpx\dispatch\connection_pool.py", line 153, in send
    response = await connection.send(request, timeout=timeout)
    return await self.connection.send(request, timeout=timeout)
  File "D:\xxx\python\bug\venv\lib\site-packages\httpx\dispatch\http11.py", line 51, in send
    await self._send_request_body(request, timeout)
  File "D:\xxx\python\bug\venv\lib\site-packages\httpx\dispatch\http11.py", line 98, in _send_request_body
    async for chunk in request.stream:
  File "D:\xxx\python\bug\venv\lib\site-packages\httpx\content_streams.py", line 112, in __aiter__
    raise RuntimeError("Attempted to call a async iterator on an sync stream.")
RuntimeError: Attempted to call a async iterator on an sync stream.
```

It seems to me that https://github.com/encode/httpx/blob/53804173bb734ce94d13d1b34c0ebaab46abd8c3/httpx/_dispatch/http11.py#L98 does not work, when there is a sync stream comming in. Maybe this is by design?

**Comment by yeraydiazdiaz** [comment] 2020-03-01 10:31
Hi @masi456, I believe it is by design to an extent, you're passing the `SpooledTemporaryFile` instance as `data` and using an `AsyncClient`, however `SpooledTemporaryFile` does not implement asynchronous iteration (`__aiter__`) so an exception is raised.

Could you elaborate on your use case? Why are you trying to use a `SpooledTemporaryFile`?

**Comment by florimondmanca** [comment] 2020-03-01 11:09
@masi456 This is by design in the sense that `data` argument on async clients only accepts objects that implement `__aiter__()`.

If the data source you're using does not implement that interface, you can always wrap it in your own async generator…

```python
import tempfile
import httpx
import asyncio

file = tempfile.SpooledTemporaryFile(mode="rw")
file.write("Hello World")

async def main():
    async with httpx.AsyncClient() as client:
        async def data():
            yield from file

        await client.put("http://localhost:9998/meta", data=data())

asyncio.run(main())
```

**Comment by masi456** [comment] 2020-03-01 12:23
> Could you elaborate on your use case? Why are you trying to use a `SpooledTemporaryFile`?

This is because I'm using fastapi, which is giving me a "SpooledTemporaryFile object that you can pass directly to other libraries that expect a file-like object" (https://fastapi.tiangolo.com/tutorial/request-files/). I tried to take that file-like object and forward it directly to another endpoint.

On a related note, when I try using the files paramter it seems to be the other way around:
```
        async with httpx.AsyncClient() as client, aiofiles.open(file, "rb") as file:
            async for x in file:
                print(x)
                
            response = await client.post(
                "http://localhost:8000/index/",
                files={"file": file}
            )
```

gives me

```
  ...
  File "D:\xxx\venv\lib\site-packages\httpx\client.py", line 1305, in post
    return await self.request(
  File "D:\xxx\venv\lib\site-packages\httpx\client.py", line 1086, in request
    request = self.build_request(
  File "D:\xxx\venv\lib\site-packages\httpx\client.py", line 204, in build_request
    return Request(
  File "D:\xxx\venv\lib\site-packages\httpx\models.py", line 614, in __init__
    self.stream = encode(data, files, json)
  File "D:\xxx\venv\lib\site-packages\httpx\content_streams.py", line 329, in encode
    return MultipartStream(data={}, files=files, boundary=boundary)
  File "D:\xxx\venv\lib\site-packages\httpx\content_streams.py", line 280, in __init__
    body.write(field.render_data())
TypeError: a bytes-like object is required, not 'generator'
```

So it seems to me that
1) files= can only take bytes-like objects while
2) data= can only take async generators

> If the data source you're using does not implement that interface, you can always wrap it in your own async generator…

Yes that's probably what I am going to do! Thank you.

**Comment by yeraydiazdiaz** [comment] 2020-03-01 16:56
Closing this as we've concluded the error is by design.

**Closed by yeraydiazdiaz** 2020-03-01 16:56 UTC
Labels: question
