### ISSUE TITLE
HTTPX returns 403, but requests 200.

### ISSUE THREAD

**Issue by fakeastap** [encode/httpx#2795] opened 2023-07-28 16:38 UTC
I'm trying to parse one site. I'm sending a naked http request, just by setting a User-Agent.

It's surprising how a request using "requests" returns a 200 response. But the same query using httpx returns 403. I have tried making the request with both the 1.1 version of the http protocol and the 2.0 version. It didn't give any result.

I know that this site uses some protection against bots.

But why does the primitive "requests" do the job, as opposed to httpx?

30 sec video: https://i.imgur.com/tWOe0sZ.mp4

httpx==0.24.1

In my thread on stackoverflow I found one user with a similar problem: https://stackoverflow.com/questions/76133055/httpx-returns-403-but-requests-200-python?noredirect=1#comment135200607_76133055.
That's why I created a topic here.

**Comment by zanieb** [comment] 2023-07-28 20:28
Thanks for the report. Would you please add your notes over in https://github.com/encode/httpx/discussions/2684 instead? This is a duplicate of that existing report. 

The tldr here is that the website is probably blindly blocking HTTPX user agents because it's been used for nefarious purposes against them.

**Closed by zanieb** 2023-07-28 20:28 UTC
