### ISSUE TITLE
Failing to detect lost connections (asyncio only)

### ISSUE THREAD

**Issue by didip** [encode/httpx#95] opened 2019-06-18 17:08 UTC
1 of 5 requests I initiated would raise ConnectionResetError('Connection lost') when calling `AsyncClient` from inside Starlette and Uvicorn.

In comparison, urllib, requests and Tornado's AsyncClient works as expected.

Stacktrace:

```
  File "/project/venv/lib/python3.7/site-packages/http3/client.py", line 145, in send_handling_redirects
    request, verify=verify, cert=cert, timeout=timeout
  File "/project/venv/lib/python3.7/site-packages/http3/dispatch/connection_pool.py", line 121, in send
    raise exc
  File "/project/venv/lib/python3.7/site-packages/http3/dispatch/connection_pool.py", line 116, in send
    request, verify=verify, cert=cert, timeout=timeout
  File "/project/venv/lib/python3.7/site-packages/http3/dispatch/connection.py", line 59, in send
    response = await self.h11_connection.send(request, timeout=timeout)
  File "/project/venv/lib/python3.7/site-packages/http3/dispatch/http11.py", line 53, in send
    await self._send_event(event, timeout)
  File "/project/venv/lib/python3.7/site-packages/http3/dispatch/http11.py", line 101, in _send_event
    await self.writer.write(data, timeout)
  File "/project/venv/lib/python3.7/site-packages/http3/concurrency.py", line 89, in write
    self.stream_writer.drain(), timeout.write_timeout
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/tasks.py", line 388, in wait_for
    return await fut
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/streams.py", line 348, in drain
    await self._protocol._drain_helper()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/streams.py", line 202, in _drain_helper
    raise ConnectionResetError('Connection lost')
```

**Comment by tomchristie** [comment] 2019-06-18 19:21
Could you break this down to the simplest possible reproduction? Which URL, what kind of request? Does it reproduce on a range of URLs, or mainly on one specific site. Can you reproduce independently of Starlette, and just demonstrate it standalone? Thanks so much!

**Comment by tomchristie** [comment] 2019-06-18 20:50
Could be that it’s caused by https://github.com/encode/http3/issues/5 - will need to replicate, and then do some digging.

**Comment by simonw** [comment] 2019-07-07 18:16
I'm seeing this bug too. Here's a recent traceback (from my Heroku logs):
```
2019-07-07T18:12:31.578437+00:00 heroku[router]: at=info method=GET path="/-/auth-callback?code=e124aa75f61efd442f86" host=datasette-auth-demo.herokuapp.com request_id=834768c7-8903-4853-98c0-5bae77ffba3e fwd="148.64.98.14" dyno=web.1 connect=1ms service=93ms status=500 bytes=212 protocol=https
2019-07-07T18:12:31.571399+00:00 app[web.1]: ERROR: Exception in ASGI application
2019-07-07T18:12:31.571413+00:00 app[web.1]: Traceback (most recent call last):
2019-07-07T18:12:31.571416+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/uvicorn/protocols/http/httptools_impl.py", line 370, in run_asgi
2019-07-07T18:12:31.571417+00:00 app[web.1]: result = await app(self.scope, self.receive, self.send)
2019-07-07T18:12:31.571419+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/datasette_auth_github/github_auth.py", line 77, in __call__
2019-07-07T18:12:31.571421+00:00 app[web.1]: return await self.auth_callback(scope, receive, send)
2019-07-07T18:12:31.571422+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/datasette_auth_github/github_auth.py", line 216, in auth_callback
2019-07-07T18:12:31.571424+00:00 app[web.1]: profile = (await self.github_api_client.get(profile_url)).json()
2019-07-07T18:12:31.571426+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/http3/client.py", line 316, in get
2019-07-07T18:12:31.571428+00:00 app[web.1]: timeout=timeout,
2019-07-07T18:12:31.571429+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/http3/client.py", line 548, in request
2019-07-07T18:12:31.571431+00:00 app[web.1]: timeout=timeout,
2019-07-07T18:12:31.571433+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/http3/client.py", line 145, in send
2019-07-07T18:12:31.571434+00:00 app[web.1]: allow_redirects=allow_redirects,
2019-07-07T18:12:31.571436+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/http3/client.py", line 178, in send_handling_redirects
2019-07-07T18:12:31.571437+00:00 app[web.1]: request, verify=verify, cert=cert, timeout=timeout
2019-07-07T18:12:31.571439+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/http3/dispatch/connection_pool.py", line 121, in send
2019-07-07T18:12:31.571441+00:00 app[web.1]: raise exc
2019-07-07T18:12:31.571442+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/http3/dispatch/connection_pool.py", line 116, in send
2019-07-07T18:12:31.571444+00:00 app[web.1]: request, verify=verify, cert=cert, timeout=timeout
2019-07-07T18:12:31.571445+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/http3/dispatch/connection.py", line 59, in send
2019-07-07T18:12:31.571447+00:00 app[web.1]: response = await self.h11_connection.send(request, timeout=timeout)
2019-07-07T18:12:31.571449+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/http3/dispatch/http11.py", line 49, in send
2019-07-07T18:12:31.571450+00:00 app[web.1]: await self._send_request(request, timeout)
2019-07-07T18:12:31.571452+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/http3/dispatch/http11.py", line 83, in _send_request
2019-07-07T18:12:31.571453+00:00 app[web.1]: await self._send_event(event, timeout)
2019-07-07T18:12:31.571455+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/http3/dispatch/http11.py", line 115, in _send_event
2019-07-07T18:12:31.571456+00:00 app[web.1]: await self.writer.write(bytes_to_send, timeout)
2019-07-07T18:12:31.571457+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/http3/concurrency.py", line 133, in write
2019-07-07T18:12:31.571459+00:00 app[web.1]: self.stream_writer.drain(), timeout.write_timeout
2019-07-07T18:12:31.571460+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
2019-07-07T18:12:31.571462+00:00 app[web.1]: return fut.result()
2019-07-07T18:12:31.571463+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/asyncio/streams.py", line 339, in drain
2019-07-07T18:12:31.571465+00:00 app[web.1]: yield from self._protocol._drain_helper()
2019-07-07T18:12:31.571466+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/asyncio/streams.py", line 210, in _drain_helper
2019-07-07T18:12:31.571468+00:00 app[web.1]: raise ConnectionResetError('Connection lost')
2019-07-07T18:12:31.571474+00:00 app[web.1]: ConnectionResetError: Connection lost
2019-07-07T18:12:31.571475+00:00 app[web.1]: INFO: ('10.13.156.79', 19351) - "GET /-/auth-callback HTTP/1.1" 500
```
Here's my code that's making the API call: https://github.com/simonw/datasette-auth-github/blob/b4bbb0ecbc66a67fe6b57dc9c47870fe8fa6c0fc/datasette_auth_github/github_auth.py#L188-L199
```python
        # Exchange that code for a token
        github_response = (
            await self.github_api_client.post(
                "https://github.com/login/oauth/access_token",
                data={
                    "client_id": self.client_id,
                    "client_secret": self.client_secret,
                    "code": qs["code"],
                },
            )
        ).text
parsed = dict(parse_qsl(github_response))
```
Where `github_api_client = http3.AsyncClient()` as a class-level property.

I'm going to try instantiating a new `AsyncClient()` each time rather than re-using one for each request.

**Comment by simonw** [comment] 2019-07-07 18:28
I changed my code to stop re-using the `AsyncClient()` instance across multiple requests and it seems to have fixed the problem for me - see https://github.com/simonw/datasette-auth-github/issues/27

**Comment by tomchristie** [comment] 2019-07-07 20:32
Gotcha - thanks for the report. Seems pretty likely it’d be occurring when attempting to use a connection that’s disconnected, eg due to keep alive timing out on the server side.

**Comment by tomchristie** [comment] 2019-07-08 15:01
Alrighty. I could recreate this issue by creating a client, issuing a request, then waiting 5+ mins, and making another request.

Version 0.6.7 properly deals with the case where an expired connection is obtained from the connection pool. In my testing this resolves the issue. 👍

**Comment by rwboyer** [comment] 2019-08-25 21:34
> Alrighty. I could recreate this issue by creating a client, issuing a request, then waiting 5+ mins, and making another request.
> 
> Version 0.6.7 properly deals with the case where an expired connection is obtained from the connection pool. In my testing this resolves the issue. 👍

I seem to be having the same sort of issue but I am running 0.7.1 using 

```
#global
client = httpx.AsyncClient()
---

#inside route
r = await client.post("https://www.google.com/recaptcha/api/siteverify", data={"secret": "MYSECRET","response": body['gresponse']})
```

I've moved client to create a new AsyncClient() inside of the route for now, am I missing something or is this the same issue as above?

**Comment by dmontagu** [comment] 2019-11-27 00:11
I'm also getting this issue with 0.7.6 with infrequent calls to an elasticsearch server.

**Comment by tomchristie** [comment] 2019-12-02 16:39
Right - I don't think that the issue here is that we're losing the connection, I think it's that we're not *detecting* that we've lost the connection.

When we acquire a connection from the pool we check if it has been closed or not... https://github.com/encode/httpx/blob/12d00b238e837a96271d7b07b8c3b456bd82fe0c/httpx/dispatch/connection_pool.py#L195

However it's been noted that the "is closed" detection on asyncio may be flaky... https://github.com/encode/httpx/issues/346#issuecomment-531593567

* Anyone want to dig into double checking that our `is_connection_dropped()` call is returning `False` in the case that this issue occurs?
* Anyone want to dig into checking that this only occurs on asyncio, and not on trio?

**Comment by tomchristie** [comment] 2019-12-02 16:41
There are potential mitigations here, such as having a keep-alive time on connections, and assuming that they're expired once the keep-alive is passed, but it'd be good to have a clear handle on if we've got to the root of the cause first.

**Comment by daxartio** [comment] 2019-12-09 13:01
How can i fix this problem? May be request retrying if i expect ConnectionResetError?

**Comment by tomchristie** [comment] 2019-12-09 13:13
@daxartio I'm looking at resolving this issue.
Until then, a cheap fix is to just use a new client on each connection.

**Closed** 2019-12-12 11:52 UTC
Labels: bug
