### ISSUE TITLE
Comparison vs aiohttp

### ISSUE THREAD

**Issue by clbarnes** [encode/httpx#1216] opened 2020-08-25 08:59 UTC
There are two major asyncio-based HTTP clients for python. Anyone wanting an asyncio-based HTTP client in python (i.e. a superset of httpx's users) therefore needs to pick between them. However, the documentation for neither refers to the other.

A look at the docs suggests their APIs are superficially similar.

In what use case should httpx be preferred? What kind of user should be redirected to aiohttp? Why are they not the same project? Given answers to these questions are valuable to all python HTTP client users (rather than just httpx users), it would be very helpful to make the distinctions clear.

[Mirror issue on the aiohttp repo](https://github.com/aio-libs/aiohttp/issues/4933). I cross-post them not to start any sort of tit-for-tat, but because it benefits the python HTTP and asyncio communities to have accurate and unbiased information available for our options.

**Comment by tomchristie** [comment] 2020-08-25 10:44
Somewhat a duplicate of #207, but yes we should.

See also https://github.com/theelous3/asks

Main headliners here for HTTPX are...

* Supports HTTP/1.1 &* HTTP/2
* Supports both synchronous and async I/O
* Supports alternate async backends besides asyncio (trio, and soon curio)
* Supports calling into ASGI and WSGI applications without I/O
* Designed for compatibility with requests, with a docs section outlining any points where the API differs.

They're not the same project because we were approaching a whole bunch of complex areas (such as how to build an HTTP client that supports both sync + async usages) that needed a clean slate, and the freedom to iterate on the design.

However we've put a stack of effort into making sure that the low-level transport layer is really tightly spec'ed as a standalone package - `httpcore`. Something we'd be very interested in would be figuring out with other projects (`asks`, `aiohttp`) if there's any mileage in figuring out if their clients would be able to use `httpcore` as their transport layer. In order to:

* Bring HTTP/2 support to those projects, with less effort than would otherwise be required.
* Be able to consolidate our efforts on the core networking layer, while still being able to provide different client libraries on top of that, and not break API for existing users.

We've not really reached out to folks about that yet since we've been focusing on getting to a 1.0 release first, but it *might* be an area worth exploring.

**Comment by clbarnes** [comment] 2020-08-25 10:48
Thanks, that's really helpful! You're right, it is a duplicate of #207, just not one I came across in my searches. Would you mind copying your comment above to that issue, and then referencing aiohttp and asks by name so that they're found by the issue search? Then this can be closed.

**Comment by tomchristie** [comment] 2020-08-25 12:03
Good call, done! 👍

**Closed by tomchristie** 2020-08-25 12:03 UTC
Labels: docs
