### ISSUE TITLE
httpx.RemoteProtocolError: can't handle event type ConnectionClosed when role=SERVER and state=SEND_RESPONSE

### ISSUE THREAD

**Issue by bryanapperson** [encode/httpx#1478] opened 2021-02-21 00:11 UTC
### Checklist

- [x] The bug is reproducible against the latest release and/or `master`.
- [x] There are no similar issues or pull requests to fix it yet.

### Describe the bug

When issuing a large amount of requests with an async client via an SSH http proxy, the client loses connection and throws an exception. This doesn't happen on localhost.

### To reproduce

My RPC adapter:

```python
class AsyncJSONRPC(object):
    def __init__(self,
                 rpc_uri: str = 'http://localhost/'):
        self.rpc_uri = rpc_uri
        self._client = self._get_httpx_client()

    async def close(self):
        await self._client.aclose()

    async def __aenter__(self):
        return self

    async def __aexit__(self, *excinfo):
        await self.close()

    def _get_httpx_client(self) -> httpx.AsyncClient:
        """Return an async httpx client pointing to ethereum_client_rpc_uri."""
        return httpx.AsyncClient(base_url=self.rpc_uri)

    async def json_rpc_request(self, body: dict) -> httpx.Response:
        """Return the response to the request."""
        response = await self._client.post(
                url=self.rpc_uri,
                json=body
            )
        return response

   async def do_thing(self) -> int:
        body = {'jsonrpc': '2.0'}
        response = await self.json_rpc_request(body)
        return response.json()['result']


class ThingDoer(object):

    async def do_many_things(self):
        things = []
        async with AsyncJSONRPC() as json_rpc:
            for i in range(1, 100000):
                things.append(json_rpc.do_thing())
            await asyncio.gather(*things)

    def run(self):
        start_time = time.monotonic()
        asyncio.run(self.do_many_things())
        print(f"Time Taken:{time.monotonic() - start_time}")

worker = ThingDoer()
worker.run()
```

### Expected behavior

The client should handle an arbitrary number of requests and then exit.

### Actual behavior

Client throws `remoteProtocolError: can't handle event type ConnectionClosed when role=SERVER and state=SEND_RESPONSE` with more than 10k requests, and more then 1k with `http2=True`.

### Debugging material

```python
unhandled exception during asyncio.run() shutdown
task: <Task finished name='Task-28345' coro=<AsyncJSONRPC.do_thing() done, defined at /home/me/Projects/test/__init__.py:43> exception=RemoteProtocolError("can't handle event type ConnectionClosed when role=SERVER and state=SEND_RESPONSE")>
Traceback (most recent call last):
  File "/home/bapperson/.cache/pypoetry/virtualenvs/test-hevE6Mis-py3.9/lib/python3.9/site-packages/httpx/_exceptions.py", line 326, in map_exceptions
    yield
  File "/home/bapperson/.cache/pypoetry/virtualenvs/test-hevE6Mis-py3.9/lib/python3.9/site-packages/httpx/_client.py", line 1502, in _send_single_request
    (status_code, headers, stream, ext,) = await transport.arequest(
  File "/home/bapperson/.cache/pypoetry/virtualenvs/test-hevE6Mis-py3.9/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 218, in arequest
    response = await connection.arequest(
  File "/home/bapperson/.cache/pypoetry/virtualenvs/test-hevE6Mis-py3.9/lib/python3.9/site-packages/httpcore/_async/connection.py", line 106, in arequest
    return await self.connection.arequest(method, url, headers, stream, ext)
  File "/home/bapperson/.cache/pypoetry/virtualenvs/test-hevE6Mis-py3.9/lib/python3.9/site-packages/httpcore/_async/http11.py", line 72, in arequest
    ) = await self._receive_response(timeout)
  File "/home/bapperson/.cache/pypoetry/virtualenvs/test-hevE6Mis-py3.9/lib/python3.9/site-packages/httpcore/_async/http11.py", line 133, in _receive_response
    event = await self._receive_event(timeout)
  File "/home/bapperson/.cache/pypoetry/virtualenvs/test-hevE6Mis-py3.9/lib/python3.9/site-packages/httpcore/_async/http11.py", line 169, in _receive_event
    event = self.h11_state.next_event()
  File "/usr/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/bapperson/.cache/pypoetry/virtualenvs/test-hevE6Mis-py3.9/lib/python3.9/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
httpcore.RemoteProtocolError: can't handle event type ConnectionClosed when role=SERVER and state=SEND_RESPONSE
```

### Environment

- OS: Linux host 5.10.14-arch1-1
- Python version: 3.9.1
- HTTPX version: 0.16.1
- Async environment: asyncio, no interest in using trio.
- HTTP proxy: Does not happen on localhost, happens when proxying connection with SSH tunnel
- Custom certificates: No

### Additional context

I was just testing throughput and encountered this. Does not happen with short lived clients. It's talking to a custom json rpc, but I don't see this issue with requests, or the non-async version of the client.

**Comment by tonal** [comment] 2021-04-05 09:25
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/httpx/_exceptions.py", line 326, in map_exceptions
    yield
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1492, in _send_single_request
    (status_code, headers, stream, ext) = await transport.arequest(
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 169, in arequest
    return await self._pool.arequest(
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 218, in arequest
    response = await connection.arequest(
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection.py", line 106, in arequest
    return await self.connection.arequest(method, url, headers, stream, ext)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/http11.py", line 72, in arequest
    ) = await self._receive_response(timeout)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/http11.py", line 133, in _receive_response
    event = await self._receive_event(timeout)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/http11.py", line 169, in _receive_event
    event = self.h11_state.next_event()
  File "/usr/local/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
httpcore.RemoteProtocolError: can't handle event type ConnectionClosed when role=SERVER and state=SEND_RESPONSE
```

**Comment by martinka** [comment] 2021-04-21 18:40
I have hit the same behavior using an http proxy.  Additionally the exception not only breaks the current request which would be ok, it seems to halt all async requests that are running using that client session.

**Comment by tomchristie** [comment] 2021-04-21 21:23
Okay. It looks like this occurs when a connection is closed prematurely without having sent the full response.

What I *really* need in order to be able to help out with this properly is a really well defined, minimal, "here's the simplest set of instructions possible that'll reliably replicate this issue".

**Comment by martinka** [comment] 2021-04-23 13:32
I will see what I can do, however its a bit hard for us to recreate, it happens after we have been running under load for about 3 days.  We are going to see if we can reproduce it in a more controlled setting.  The one other thing I will point out, is while the error messages says the role is SERVER, we are only using httpx as a client, and have no control over the server.  I am wondering if there is some portion of the code that is being incorrectly run.

**Comment by tomchristie** [comment] 2021-04-23 13:55
No, it just means that there's been a protocol violation in the server response. Which in this case is likely a premature termination of the socket when the response was midway through being sent.

**Comment by ahopkins** [comment] 2021-04-26 07:41
FYI - I am experiencing this as well. The issue does not come up in localhost testing, but as soon as we deploy to our k8s cluster this appears. For reference, we **do** control both sides of the request. The HTTP messages are internal to the same cluster. There is a proxy layer in between, so let me try and get some details, and I will also try and come up with a reproducible example.

**Comment by tomchristie** [comment] 2021-04-28 15:02
Okay, so actually I think this is occurring when the server closes the connection without sending a response.

You can reproduce the issue like so...

```python
import asyncio


async def server_with_close_instead_of_response():
    async def close_instead_of_response(reader, writer):
        # Wait for an incoming request and then close the connection.
        await reader.readuntil(b"\r\n\r\n")
        writer.close()

    server = await asyncio.start_server(close_instead_of_response, "127.0.0.1", 8888)
    async with server:
        await server.serve_forever()

asyncio.run(server_with_close_instead_of_response())
```

Then you'll see the following behaviour...

```pycon
>>> import httpx
>>> httpx.get("http://127.0.0.1:8888/")
Traceback (most recent call last):
  File "/Users/tomchristie/GitHub/encode/httpx/httpx/_transports/default.py", line 61, in map_httpcore_exceptions
    yield
  File "/Users/tomchristie/GitHub/encode/httpx/httpx/_transports/default.py", line 183, in handle_request
    extensions=extensions,
  File "/Users/tomchristie/GitHub/encode/httpx/venv/lib/python3.7/site-packages/httpcore/_sync/connection_pool.py", line 223, in handle_request
    method, url, headers=headers, stream=stream, extensions=extensions
  File "/Users/tomchristie/GitHub/encode/httpx/venv/lib/python3.7/site-packages/httpcore/_sync/connection.py", line 109, in handle_request
    method, url, headers, stream, extensions
  File "/Users/tomchristie/GitHub/encode/httpx/venv/lib/python3.7/site-packages/httpcore/_sync/http11.py", line 69, in handle_request
    ) = self._receive_response(timeout)
  File "/Users/tomchristie/GitHub/encode/httpx/venv/lib/python3.7/site-packages/httpcore/_sync/http11.py", line 130, in _receive_response
    event = self._receive_event(timeout)
  File "/Users/tomchristie/GitHub/encode/httpx/venv/lib/python3.7/site-packages/httpcore/_sync/http11.py", line 166, in _receive_event
    event = self.h11_state.next_event()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/tomchristie/GitHub/encode/httpx/venv/lib/python3.7/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
httpcore.RemoteProtocolError: can't handle event type ConnectionClosed when role=SERVER and state=SEND_RESPONSE

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tomchristie/GitHub/encode/httpx/httpx/_api.py", line 196, in get
    trust_env=trust_env,
  File "/Users/tomchristie/GitHub/encode/httpx/httpx/_api.py", line 110, in request
    allow_redirects=allow_redirects,
  File "/Users/tomchristie/GitHub/encode/httpx/httpx/_client.py", line 749, in request
    request, auth=auth, allow_redirects=allow_redirects, timeout=timeout
  File "/Users/tomchristie/GitHub/encode/httpx/httpx/_client.py", line 837, in send
    history=[],
  File "/Users/tomchristie/GitHub/encode/httpx/httpx/_client.py", line 871, in _send_handling_auth
    history=history,
  File "/Users/tomchristie/GitHub/encode/httpx/httpx/_client.py", line 901, in _send_handling_redirects
    response = self._send_single_request(request, timeout)
  File "/Users/tomchristie/GitHub/encode/httpx/httpx/_client.py", line 940, in _send_single_request
    extensions={"timeout": timeout.as_dict()},
  File "/Users/tomchristie/GitHub/encode/httpx/httpx/_transports/default.py", line 183, in handle_request
    extensions=extensions,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/tomchristie/GitHub/encode/httpx/httpx/_transports/default.py", line 78, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.RemoteProtocolError: can't handle event type ConnectionClosed when role=SERVER and state=SEND_RESPONSE
```

Or with requests, you'll get a more obvious exception...

```pycon
>>> import requests
>>> requests.get("http://127.0.0.1:8888/")
Traceback (most recent call last):
  File "/Users/tomchristie/GitHub/encode/httpx/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/Users/tomchristie/GitHub/encode/httpx/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/tomchristie/GitHub/encode/httpx/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1344, in getresponse
    response.begin()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 275, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tomchristie/GitHub/encode/httpx/venv/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Users/tomchristie/GitHub/encode/httpx/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/Users/tomchristie/GitHub/encode/httpx/venv/lib/python3.7/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/tomchristie/GitHub/encode/httpx/venv/lib/python3.7/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/Users/tomchristie/GitHub/encode/httpx/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/Users/tomchristie/GitHub/encode/httpx/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/tomchristie/GitHub/encode/httpx/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1344, in getresponse
    response.begin()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 275, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tomchristie/GitHub/encode/httpx/venv/lib/python3.7/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/tomchristie/GitHub/encode/httpx/venv/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/tomchristie/GitHub/encode/httpx/venv/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/tomchristie/GitHub/encode/httpx/venv/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/tomchristie/GitHub/encode/httpx/venv/lib/python3.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

**Comment by ahopkins** [comment] 2021-04-29 05:35
I can confirm this. What I found in my testing was that a `httpx.AsyncClient` was being instantiated and used multiple times:

```python
client = httpx.AsyncClient()
...
async with client as c:
    await c.get(...)
```

Therefore (and I am assuming this without digging too deeply into the code), on `__aexit__` all connections using that client are closed when the first one exits, which results in this error.

**Comment by ahopkins** [comment] 2021-04-29 05:46
Here's a short snippet to reproduce.

*Server where one request is longer than the other*
```python
import asyncio

from sanic import Sanic, text

app = Sanic(__name__)


@app.get("/<num:int>")
async def handler(request, num):
    if not num:
        await asyncio.sleep(1)
    return text(request.ip)


app.run(port=9999, debug=True)
```

*Client that issues two requests: the first response taking longer than the second*
```python
import asyncio

import httpx


async def do_call(httpx_client, num):
    async with httpx_client as client:
        await client.get(f"http://localhost:9999/{num}")


async def run():
    httpx_client = httpx.AsyncClient()
    loop = asyncio.get_running_loop()

    tasks = [loop.create_task(do_call(httpx_client, i)) for i in range(2)]
    await asyncio.gather(*tasks)


asyncio.run(run())
```

**Comment by tomchristie** [comment] 2021-04-29 10:54
Thanks @ahopkins that's super helpful.

I've raised an issue in #1614 to help us track better error messaging in this case.

The fix is to ensure the correct scoping for the client instance...

```python
import asyncio

import httpx


async def do_call(httpx_client, num):
    await client.get(f"http://localhost:9999/{num}")


async def run():
    async with httpx.AsyncClient() as client:
        loop = asyncio.get_running_loop()
        tasks = [loop.create_task(do_call(client, i)) for i in range(2)]
        await asyncio.gather(*tasks)


asyncio.run(run())
```

But for sure, the exception we're raising here isn't helping to make this clear in any way.

**Comment by ahopkins** [comment] 2021-04-29 10:56
Absolutely, once I tracked down and found the issue I realized it was a problem with implementation. The error message though (as you said) was not an obvious indication of what was happening.

**Comment by tomchristie** [comment] 2021-04-29 13:06
Closing this off now, since:

* `httpcore` 0.13.1 will now raise a more descriptive error here. "Server closed without sending response."
* Issues #1614 and #1615 have been raised for tighter errors around prematurely closed clients.

**Closed by tomchristie** 2021-04-29 13:06 UTC

**Comment by FuckingToasters** [comment] 2022-09-05 13:02
I get the same issue when simply using proxies in a client request working with threads. if i don't use a proxy everything is fine but after a while this error "Server closed without sending response" happen. I'm not using async code atm. anyone could help me there?
