### ISSUE TITLE
add more type checking in params/form-data

### ISSUE THREAD

**Issue by trim21** [encode/httpx#3170] opened 2024-04-17 11:54 UTC
- [ ] Initially raised as discussion #3168

# Problem
we should check input value types. Current behavoir which simply convert input value to `str(v)` is not very ideal.

for example:
```py
import httpx


r = httpx.post(
    "https://httpbin.org/post",
    data={
        "content": bytes.fromhex(
            "4f5f13d16da9f10d013933673a1ef4e7b974dbe3"
        ),  # random non-printable bytes
    },
)
print(r.json()["form"])
```

will get `{'content': "b'O_\\x13\\xd1m\\xa9\\xf1\\r\\x0193g:\\x1e\\xf4\\xe7\\xb9t\\xdb\\xe3'"}`

# Proposal

add type checking and more coerce.

for example:

## form

- convert `int`/`float` to str with `str(v)`
- `bool` (Represent as JSON-style "true"/"false")
- `None` (Represent as empty string)
- `Enum` (Use .value and then as above.)
- `TypeError` for anything else.

## query
except about, query should support `bytes` with percent encoding and do not throw.

## multipart_data

not sure how to handle this....

This will cause breaking changes, so we should consider do a minor version bump.

---

related: https://github.com/encode/httpx/issues/1500 https://github.com/encode/httpx/pull/1539 https://github.com/encode/httpx/pull/1608

https://github.com/encode/httpx/blob/4b85e6c3898b94e686b427afd83138c87520b479/httpx/_content.py#L136-L149

https://github.com/encode/httpx/blob/4b85e6c3898b94e686b427afd83138c87520b479/httpx/_utils.py#L56-L68

**Comment by trim21** [comment] 2024-05-31 13:38
there is also another issue, query string support bytes natively.

for example:

```python
import httpx
import urllib.parse

r = httpx.get(
    "https://httpbin.org/get",
    params={"q": bytes.fromhex("E1EE0E2734986F5419BB6CB6252BD9377183440E")},
)

print(urllib.parse.quote(bytes.fromhex("E1EE0E2734986F5419BB6CB6252BD9377183440E")))

print(r.text)
```

expected url should be `https://httpbin.org/get?q=%E1%EE%0E%274%98oT%19%BBl%B6%25%2B%D97q%83D%0E`, instead of ValueError or TypeError

**Comment by tomchristie** [comment] 2024-06-03 10:43
> query string should support bytes natively.

I'm not convinced by that. Why?

**Comment by trim21** [comment] 2024-06-03 10:47
> > query string should support bytes natively.
> 
> I'm not convinced by that. Why?

because percent encoding can take native bytes as input

**Comment by trim21** [comment] 2024-06-03 10:53
when we say it support "string", it's actually supporting string encoded in utf8.

consider this:

```python
from urllib.parse import quote, quote_from_bytes


utf8_s = "你好"

assert quote(utf8_s) == quote_from_bytes(utf8_s.encode())
```


`https://example.com/?q=%E4%BD%A0%E5%A5%BD`

**Comment by tomchristie** [comment] 2024-06-03 11:18
I think this is confusing a couple of separate issues...

* Should str-coercion be performed.
* Should bytes be a supported type.

I'm think there's a good case that we shouldn't str-coerce types outside of the expected range. I don't currently think there's a good case that we should support bytes.

**Comment by trim21** [comment] 2024-06-03 11:24
I would vote for both...

consider this:

```python
httpx.get("https://example.com/?q=%E1%EE%0E%274%98oT%19%BBl%B6%25%2B%D97q%83D%0E", params={"a": 1})
```

looks fine, right?

but actually request url is `?q=%EF%BF%BD%EF%BF%BD%0E%274%EF%BF%BDoT%19%EF%BF%BDl%EF%BF%BD%25%2B%EF%BF%BD7q%EF%BF%BDD%0E&a=1`, which it not right.

**Comment by cknv** [comment] 2024-06-03 11:34
Just to chip in a bit here:

I have been using httpx to interact with a legacy system and as test client to mimic that legacy system calling back into our starlette based API.
Some of the query fields can occasionally be bytes, these bytes are either just bytes that only has meaning to systems outside of my control, or UTF-16 encoded strings (which as an aside can also mean that I have to produce a mixed content query string).

In order to get the correct values through httpx and not `'b"value"' I have had to resort to manually building the query myself with the stdlib and appending it on the URL.
This does work, but it took some time to arrive at and I wouldn't exactly call it "ergonomic".

But I also realize that my case is not common.

**Comment by tomchristie** [comment] 2024-06-03 16:57
> consider this (...)

```python
httpx.get("https://example.com/?q=%E1%EE%0E%274%98oT%19%BBl%B6%25%2B%D97q%83D%0E", params={"a": 1})
```

This is valid, tho simplify it...

```python
>>> r = httpx.get('https://www.example.com?q=%EE', params={'a': '1'})
>>> r.request.url
URL('https://www.example.com?q=%EF%BF%BD&a=1')
```

Simplify it more...

```python
>>> httpx.QueryParams('q=%EE')
QueryParams('q=%EF%BF%BD')
```

Eh?

Root cause is...

```python
>>> from urllib.parse import unquote
>>> from urllib.parse import quote
>>> quote(unquote('%EE'))  # stdlib behaving similarly
'%EF%BF%BD'
>>> unquote('%EE')  # The hex code here isn't a valid UTF-8 codepoint, and is being replaced.
'�'
>>> unquote('%EE', errors='strict')  # We'd raise an error if we decoded it with 'strict'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tom.christie/.pyenv/versions/3.10.6/lib/python3.10/urllib/parse.py", line 667, in unquote
    append(unquote_to_bytes(bits[i]).decode(encoding, errors))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xee in position 0: unexpected end of data
```

**Comment by trim21** [comment] 2024-06-03 17:01
> > consider this (...)
> 
> ```python
> httpx.get("https://example.com/?q=%E1%EE%0E%274%98oT%19%BBl%B6%25%2B%D97q%83D%0E", params={"a": 1})
> ```
> 
> This is valid, tho simplify it...
> 
> ```python
> >>> r = httpx.get('https://www.example.com?q=%EE', params={'a': '1'})
> >>> r.request.url
> URL('https://www.example.com?q=%EF%BF%BD&a=1')
> ```
> 
> Simplify it more...
> 
> ```python
> >>> httpx.QueryParams('q=%EE')
> QueryParams('q=%EF%BF%BD')
> ```
> 
> Eh?
> 
> Root cause is...
> 
> ```python
> >>> from urllib.parse import unquote
> >>> from urllib.parse import quote
> >>> quote(unquote('%EE'))  # stdlib behaving similarly
> '%EF%BF%BD'
> >>> unquote('%EE')  # The hex code here isn't a valid UTF-8 codepoint, and is being replaced.
> '�'
> >>> unquote('%EE', errors='strict')  # We'd raise an error if we decoded it with 'strict'
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Users/tom.christie/.pyenv/versions/3.10.6/lib/python3.10/urllib/parse.py", line 667, in unquote
>     append(unquote_to_bytes(bits[i]).decode(encoding, errors))
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xee in position 0: unexpected end of data
> ```

yes, that's a problem, I think.

**Comment by tomchristie** [comment] 2024-06-03 17:10
@cknv Could you give a (simplified) example please?

**Comment by cknv** [comment] 2024-06-03 19:08
Sure @tomchristie! Get ready for some flashback to the dark ages, before UTF8 won the encoding wars.

```python
from urllib.parse import urlencode
import httpx

client = httpx.Client()

values = {
    "expected-as-utf8": "Hello world",
    "expected-as-int": 1234,
    "expected-as-latin1": "Hello world".encode("latin1"),
    "expected-as-binary": b"\x01\x02\x03\x04",
}

encoded_query = urlencode(values)

# replaced .get with .build_request
# as making requests does not seem important for demonstrating my workaround
correctly_encoded_request = client.build_request(
    method="GET",
    url=f"http://localhost?{encoded_query}",
)
incorrecty_encoded_request = client.build_request(
    method="GET",
    url="http://localhost",
    params=values,
)

# compare and contrast:
print(correctly_encoded_request.url.params)
print(incorrecty_encoded_request.url.params)
```
When actually rereading the code, it wasn't UTF-16 that was used, but instead actually latin1, so I replaced that in the example, although either of them would need to be encoded into bytes.

Narrowing our focus to just the plain byte value, it should be `expected-as-binary=%01%02%03%04`, and my workaround indeed does produce that.
Without the workaround and just feeding the `values` dict into the request builders `params` the value is `repr`d (via `str`) and produces `expected-as-binary=b%27%5Cx01%5Cx02%5Cx03%5Cx04%27` which is the percent encoded version of `expected-as-binary=b'\x01\x02\x03\x04'`.

The latin1 value works without the workaround as long as you stick to the subset that is identical with ASCII, but we do at times get data through that isn't just that subset.

To add some context the server receiving the request is written in C, and has a very lax attitude to encodings because _it's all just bytes anyway_.

If httpx would percent encode bytes, I would probably be able to remove that workaround. However I would not be surprised if there are other ways to send bytes over http either established in an RFC or just by tradition, if so I would not know which one is the most appropriate, but it appears like percent encoding is at least [in the RFC](https://datatracker.ietf.org/doc/html/rfc3986#section-2.1).

Finally, I would like to reiterate that I know that this is way outside the mainstream, I have mostly accepted my workaround, but I at least wanted to raise my hand when someone else expressed a similar problem.

**Comment by Graeme22** [comment] 2024-07-30 16:24
+1 for using `.value` for `Enum`s in param encoding

**Comment by trim21** [comment] 2024-08-27 14:52
any news on this？

**Comment by tomchristie** [comment] 2024-08-27 18:21
Currently I'd suggest we sharpen up on this and raise type errors on non-string values... https://github.com/encode/httpx/issues/3176#issuecomment-2313220498

HTML form encoding only supports strings, let's help our users be explicit here.

**Comment by trim21** [comment] 2024-08-27 23:51
> HTML form encoding only supports strings, let's help our users be explicit here.

This is not true.

HTML form can be `application/x-www-form-urlencoded`, which is same encoding we used in url query, which suport any binary data.

for urlencoded data, browsers have `URLSearchParams`, which support any binary data.

https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams#preserving_plus_signs

**Comment by trim21** [comment] 2024-08-28 01:01
> Currently I'd suggest we sharpen up on this and raise type errors on non-string values... [#3176 (comment)](https://github.com/encode/httpx/issues/3176#issuecomment-2313220498)
> 
> HTML form encoding only supports strings, let's help our users be explicit here.

After seconds thoughts, I think HTML have different definitions of string as we have in Python worlds.

In HTML, string can be any encoding， but it's false in python.

**Comment by tomchristie** [comment] 2024-09-27 10:57
I'm going to close this off in favor of the broader issue #3176.

**Closed by tomchristie** 2024-09-27 10:57 UTC
