### ISSUE TITLE
What behavior do we expect when a server issues an incorrect Content-Length?

### ISSUE THREAD

**Issue by dalf** [encode/httpx#643] opened 2019-12-17 14:26 UTC
```python
resp = await httpx.get('https://skyn3t.in/srx/') 
```

This URL raises an exception
```
~/code/searx-docker/searx-stats2/ve/lib/python3.6/site-packages/httpx/models.py in aiter_raw(self)
    983 
    984             self.is_stream_consumed = True
--> 985             async for part in self._raw_stream:
    986                 yield part
    987             await self.close()

~/code/searx-docker/searx-stats2/ve/lib/python3.6/site-packages/httpx/dispatch/http11.py in _receive_response_data(self, timeout)
    139         """
    140         while True:
--> 141             event = await self._receive_event(timeout)
    142             if isinstance(event, h11.Data):
    143                 yield bytes(event.data)

~/code/searx-docker/searx-stats2/ve/lib/python3.6/site-packages/httpx/dispatch/http11.py in _receive_event(self, timeout)
    160                 )
    161                 if self.socket.is_connection_dropped():
--> 162                     raise ConnectionClosed(e)
    163                 raise ProtocolError(e)
    164 

ConnectionClosed: peer closed connection without sending complete message body (received 3743 bytes, expected 11628)
```

There is no issue if gzip encoding is disabled:
```python
resp = await httpx.get('https://skyn3t.in/srx/', headers={'Accept-Encoding': 'identity'}) 
```

curl, and browsers don't see an error.

```sh
$ curl --compressed -vvvv https://skyn3t.in/srx/ 
...
> GET /srx/ HTTP/1.1
> Host: skyn3t.in
> User-Agent: curl/7.58.0
> Accept: */*
> Accept-Encoding: deflate, gzip
> 
< HTTP/1.1 200 OK
< Content-Type: text/html; charset=utf-8
< Content-Length: 11628
< Server-Timing: total;dur=9.02
< Content-Encoding: gzip
```

**Comment by tomchristie** [comment] 2019-12-18 06:44
Thanks for raising this. Is the issue occurring reliably?
Does it occur if using trio, or only with asynio?

**Comment by dalf** [comment] 2019-12-18 09:53
Yes the issue occurs reliably with asyncio and trio (using ipython or with .py file).

```
In [2]: resp = await httpx.get('https://skyn3t.in/srx/')
TRACE [2019-12-18 10:40:29] httpx.dispatch.connection_pool - acquire_connection origin=Origin(scheme='https' host='skyn3t.in' port=443)
TRACE [2019-12-18 10:40:29] httpx.dispatch.connection_pool - new_connection connection=HTTPConnection(origin=Origin(scheme='https' host='skyn3t.in' port=443))
TRACE [2019-12-18 10:40:29] httpx.config - load_ssl_context verify=True cert=None trust_env=True http2=False
TRACE [2019-12-18 10:40:29] httpx.config - load_verify_locations cafile=/home/alexandre/code/httpx/ve/lib/python3.6/site-packages/certifi-2019.11.28-py3.6.egg/certifi/cacert.pem
TRACE [2019-12-18 10:40:29] httpx.dispatch.connection - start_connect tcp host='skyn3t.in' port=443 timeout=Timeout(timeout=5.0)
TRACE [2019-12-18 10:40:31] httpx.dispatch.connection - connected http_version='HTTP/1.1'
TRACE [2019-12-18 10:40:31] httpx.dispatch.http11 - send_headers method='GET' target='/srx/' headers=Headers({'host': 'skyn3t.in', 'user-agent': 'python-httpx/0.9.4', 'accept': '*/*', 'accept-encoding': 'gzip, deflate', 'connection': 'keep-alive'})
TRACE [2019-12-18 10:40:31] httpx.dispatch.http11 - receive_event event=NEED_DATA
TRACE [2019-12-18 10:40:31] httpx.dispatch.http11 - receive_event event=Response(status_code=200, headers=[(b'content-type', b'text/html; charset=utf-8'), (b'content-length', b'11628'), (b'server-timing', b'total;dur=8.941'), (b'content-encoding', b'gzip')], http_version=b'1.1', reason=b'OK')
DEBUG [2019-12-18 10:40:31] httpx.client - HTTP Request: GET https://skyn3t.in/srx/ "HTTP/1.1 200 OK"
TRACE [2019-12-18 10:40:31] httpx.dispatch.http11 - receive_event event=Data(<3743 bytes>)
TRACE [2019-12-18 10:40:31] httpx.dispatch.http11 - receive_event event=NEED_DATA
DEBUG [2019-12-18 10:40:31] httpx.dispatch.http11 - h11.RemoteProtocolError exception their_state=ERROR error_status_hint=400
TRACE [2019-12-18 10:40:31] httpx.dispatch.http11 - response_closed our_state=MUST_CLOSE their_state=ERROR
TRACE [2019-12-18 10:40:31] httpx.dispatch.http11 - send_event event=ConnectionClosed()
TRACE [2019-12-18 10:40:31] httpx.dispatch.connection_pool - release_connection connection=HTTPConnection(origin=Origin(scheme='https' host='skyn3t.in' port=443))
```

```
In [3]: resp = await httpx.get('https://skyn3t.in/srx/', headers={'Accept-Encoding': 'identity'})
TRACE [2019-12-18 10:42:17] httpx.dispatch.connection_pool - acquire_connection origin=Origin(scheme='https' host='skyn3t.in' port=443)
TRACE [2019-12-18 10:42:17] httpx.dispatch.connection_pool - new_connection connection=HTTPConnection(origin=Origin(scheme='https' host='skyn3t.in' port=443))
TRACE [2019-12-18 10:42:17] httpx.config - load_ssl_context verify=True cert=None trust_env=True http2=False
TRACE [2019-12-18 10:42:17] httpx.config - load_verify_locations cafile=/home/alexandre/code/httpx/ve/lib/python3.6/site-packages/certifi-2019.11.28-py3.6.egg/certifi/cacert.pem
TRACE [2019-12-18 10:42:17] httpx.dispatch.connection - start_connect tcp host='skyn3t.in' port=443 timeout=Timeout(timeout=5.0)
TRACE [2019-12-18 10:42:18] httpx.dispatch.connection - connected http_version='HTTP/1.1'
TRACE [2019-12-18 10:42:18] httpx.dispatch.http11 - send_headers method='GET' target='/srx/' headers=Headers({'host': 'skyn3t.in', 'user-agent': 'python-httpx/0.9.4', 'accept': '*/*', 'connection': 'keep-alive', 'accept-encoding': 'identity'})
TRACE [2019-12-18 10:42:18] httpx.dispatch.http11 - receive_event event=NEED_DATA
TRACE [2019-12-18 10:42:18] httpx.dispatch.http11 - receive_event event=Response(status_code=200, headers=[(b'content-type', b'text/html; charset=utf-8'), (b'content-length', b'11628'), (b'server-timing', b'total;dur=12.413')], http_version=b'1.1', reason=b'OK')
DEBUG [2019-12-18 10:42:18] httpx.client - HTTP Request: GET https://skyn3t.in/srx/ "HTTP/1.1 200 OK"
TRACE [2019-12-18 10:42:18] httpx.dispatch.http11 - receive_event event=Data(<3981 bytes>)
TRACE [2019-12-18 10:42:18] httpx.dispatch.http11 - receive_event event=NEED_DATA
TRACE [2019-12-18 10:42:18] httpx.dispatch.http11 - receive_event event=Data(<4096 bytes>)
TRACE [2019-12-18 10:42:18] httpx.dispatch.http11 - receive_event event=NEED_DATA
TRACE [2019-12-18 10:42:18] httpx.dispatch.http11 - receive_event event=Data(<3551 bytes>)
TRACE [2019-12-18 10:42:18] httpx.dispatch.http11 - receive_event event=EndOfMessage(headers=[])
TRACE [2019-12-18 10:42:18] httpx.dispatch.http11 - response_closed our_state=DONE their_state=DONE
TRACE [2019-12-18 10:42:18] httpx.dispatch.connection_pool - release_connection connection=HTTPConnection(origin=Origin(scheme='https' host='skyn3t.in' port=443))
TRACE [2019-12-18 10:42:18] httpx.dispatch.connection - close_connection
TRACE [2019-12-18 10:42:18] httpx.dispatch.http11 - send_event event=ConnectionClosed()
```

**Comment by tomchristie** [comment] 2019-12-18 10:04
This does appear to *somewhat* replicate with `curl`...

```shell
$ curl --compressed -vvvv https://skyn3t.in/srx/ 
*   Trying 45.23.105.21...
* TCP_NODELAY set
* Connected to skyn3t.in (45.23.105.21) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
...
* TLSv1.2 (IN), TLS alert, Client hello (1):
* transfer closed with 7885 bytes remaining to read
* stopped the pause stream!
* Closing connection 0
* TLSv1.2 (OUT), TLS alert, Client hello (1):
curl: (18) transfer closed with 7885 bytes remaining to read
```

Note the "ransfer closed with 7885 bytes remaining to read" message there.

Presumably the response is being issued with an incorrect Content-Length header. (It *looks* to me like it is showing the Content-Length of the *decoded* content, rather than the Content-Length of the actual gzip'ed response content.

`requests` happens to handle this case without error...

```python
>>> requests.get('https://skyn3t.in/srx/')
<Response [200]>
```

However, it's not obvious if we *ought* to raise an error here or not, since we probably can't distinguish between "this was a clear close, the Content-Length just happened to be wrong" vs. "the connection was prematurely terminated".

**Comment by tomchristie** [comment] 2019-12-18 10:13
Note that I've confirmed that the server is sending the Content-Length of the unencoded content, rather than the *actual* Content-Length of the response.

```
$ curl --compressed -vvvv https://skyn3t.in/srx/ > ./test.txt
> GET /srx/ HTTP/1.1
> Host: skyn3t.in
> User-Agent: curl/7.54.0
> Accept: */*
> Accept-Encoding: deflate, gzip
> 
< HTTP/1.1 200 OK
< Content-Type: text/html; charset=utf-8
< Content-Length: 11628
...  response actually sends 3743 bytes, not 11628 ...
* transfer closed with 7885 bytes remaining to read

$ wc ./test.txt 
     441    1063   11628 ./test.txt
```

**Comment by dalf** [comment] 2019-12-18 10:30
Okay ! I understand.
Is it possible to have a ```strict_http_protocol``` parameter in ```httpx.Client.__init__``` ?
(*) or named ```lazy_http_protocol```, ```lazy_parsing```, or ...

but I guess a good default configuration is a better choice.

**Comment by tomchristie** [comment] 2019-12-18 10:37
Yeah, well at least a couple of questions here really...

* What *exactly* do we want the default behavior to be here?
* Is there any additional configuration we might want to provide for more lax behaviours?

I think that our "ConnectionClosed: peer closed connection without sending complete message body (received 3743 bytes, expected 11628)" error messaging here is pretty good, so *for the moment* we probably want to treat this as "we're doing the right thing here" and close the issue for now.

It's possible that once we've gotten to 1.0, and become a bit more mature we might want to reconsider *if* there are any alternate strategies that can handle this kind of server error more gracefully or not. (Might depend on eg. us gaining some more real world experiance of how common it is for a server to advertise the unencoded Content-Length, instead of the actual gzip'ed Content-Length.)

**Closed by tomchristie** 2019-12-18 10:37 UTC
Labels: user-experience

**Comment by csrgxtu** [comment] 2023-12-02 12:21
I met this issue too, how can i solve this?

'httpcore.RemoteProtocolError: peer closed connection without sending complete message body (received 2719744 bytes, expected 12556034)'
