### ISSUE TITLE
Error parsing IPv6

### ISSUE THREAD

**Issue by Orion-zhen** [encode/httpx#2674] opened 2023-04-20 05:19 UTC
## Environments
Ubuntu 22.04 LTS, httpx==0.24.0

## What happened?
I followed instructions in stable-diffusion-webui:
```shell
bash <(wget -qO- https://raw.githubusercontent.com/AUTOMATIC1111/stable-diffusion-webui/master/webui.sh)
```
and found an error:
```shell
Launching Web UI with arguments:
Traceback (most recent call last):
  File "/stable-diffusion-webui/venv/lib/site-packages/httpx/_urlparse.py", line 339, in normalize_port
    port_as_int = int(port)
ValueError: invalid literal for int() with base 10: ':1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/stable-diffusion-webui/launch.py", line 356, in <module>
    start()
  File "/stable-diffusion-webui/launch.py", line 347, in start
    import webui
  File "/stable-diffusion-webui/webui.py", line 25, in <module>
    import gradio
  File "/stable-diffusion-webui/venv/lib/site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "/stable-diffusion-webui/venv/lib/site-packages/gradio/components.py", line 32, in <module>
    from gradio import media_data, processing_utils, utils
  File "/stable-diffusion-webui/venv/lib/site-packages/gradio/processing_utils.py", line 25, in <module>
    from gradio import utils
  File "/stable-diffusion-webui/venv/lib/site-packages/gradio/utils.py", line 555, in <module>
    class AsyncRequest:
  File "/stable-diffusion-webui/venv/lib/site-packages/gradio/utils.py", line 575, in AsyncRequest
    client = httpx.AsyncClient()
  File "/stable-diffusion-webui/venv/lib/site-packages/httpx/_client.py", line 1408, in __init__
    self._mounts: typing.Dict[URLPattern, typing.Optional[AsyncBaseTransport]] = {
  File "/stable-diffusion-webui/venv/lib/site-packages/httpx/_client.py", line 1409, in <dictcomp>
    URLPattern(key): None
  File "/stable-diffusion-webui/venv/lib/site-packages/httpx/_utils.py", line 397, in __init__
    url = URL(pattern)
  File "/stable-diffusion-webui/venv/lib/site-packages/httpx/_urls.py", line 113, in __init__
    self._uri_reference = urlparse(url, **kwargs)
  File "/stable-diffusion-webui/venv/lib/site-packages/httpx/_urlparse.py", line 246, in urlparse
    parsed_port: typing.Optional[int] = normalize_port(port, scheme)
  File "/stable-diffusion-webui/venv/lib/site-packages/httpx/_urlparse.py", line 341, in normalize_port
    raise InvalidURL("Invalid port")
httpx.InvalidURL: Invalid port
```
## Debug
I added a debug print in _urls.py, line 113:
```python
if isinstance(url, str):
    print(url)
    self._uri_reference = urlparse(url, **kwargs)
```
and got result below:
```shell
http://127.0.0.1:somePort
http://127.0.0.1:somePort
http://
https://
all://*localhost
all://*127.0.0.1
all://*::1
```
It seems that httpx parsed all proxy-related environment variables, and "all://*::1" is related to my `no_proxy` variable.

## Solution
I simply added this to _urls.py, line 113:
```python
if url == "all://*::1":
    url = "all://*:1"
```
or you can replace "::" with ":"
```python
url = url.replace("::", ":", -1)
```
however, I think it's better to support IPv6 pasing.

## Reference
> https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/9576#issue-1664379998
>https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/9576#issuecomment-1509505604

**Comment by tomchristie** [comment] 2023-04-20 11:46
I'd assume this is a duplicate of #2659, but I've also implemented #2675 so that we'll have more informative error messages here.

We'll have a new release out soon enough.

**Closed by tomchristie** 2023-04-20 11:46 UTC
