### ISSUE TITLE
"The read operation timed out" Exception that doesn't happen when using requests

### ISSUE THREAD

**Issue by josh-marshall-jax** [encode/httpx#1030] opened 2020-06-20 02:06 UTC
### Checklist

- [?] The bug is reproducible against the latest release and/or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

Using an admittedly poorly implemented REST endpoint, I am getting a read timeout after less than 5 seconds into a POST when the identical requests usage works.

### To reproduce

```
httpx.post(
    clarity_lims_batch_url,
    auth=(username, password),
    data=element_parent.toxml(),
    headers={"Content-Type": "application/xml"},
)
```

### Expected behavior

Runs without exception

### Actual behavior

Read Timeout Exception

### Debugging material

```
Traceback (most recent call last):
  File "./CS test data.py", line 647, in <module>
    main(
  File "./CS test data.py", line 575, in main
    get_batches_for_covid_samples(
  File "./CS test data.py", line 116, in get_batches_for_covid_samples
    tmp = httpx.post(
  File "/home/marshjo/.local/lib/python3.8/site-packages/httpx/_api.py", line 269, in post
    return request(
  File "/home/marshjo/.local/lib/python3.8/site-packages/httpx/_api.py", line 86, in request
    return client.request(
  File "/home/marshjo/.local/lib/python3.8/site-packages/httpx/_client.py", line 600, in request
    return self.send(
  File "/home/marshjo/.local/lib/python3.8/site-packages/httpx/_client.py", line 620, in send
    response = self.send_handling_redirects(
  File "/home/marshjo/.local/lib/python3.8/site-packages/httpx/_client.py", line 647, in send_handling_redirects
    response = self.send_handling_auth(
  File "/home/marshjo/.local/lib/python3.8/site-packages/httpx/_client.py", line 684, in send_handling_auth
    response = self.send_single_request(request, timeout)
  File "/home/marshjo/.local/lib/python3.8/site-packages/httpx/_client.py", line 714, in send_single_request
    ) = transport.request(
  File "/home/marshjo/.local/lib/python3.8/site-packages/httpcore/_sync/connection_pool.py", line 152, in request
    response = connection.request(
  File "/home/marshjo/.local/lib/python3.8/site-packages/httpcore/_sync/connection.py", line 78, in request
    return self.connection.request(method, url, headers, stream, timeout)
  File "/home/marshjo/.local/lib/python3.8/site-packages/httpcore/_sync/http11.py", line 62, in request
    ) = self._receive_response(timeout)
  File "/home/marshjo/.local/lib/python3.8/site-packages/httpcore/_sync/http11.py", line 115, in _receive_response
    event = self._receive_event(timeout)
  File "/home/marshjo/.local/lib/python3.8/site-packages/httpcore/_sync/http11.py", line 145, in _receive_event
    data = self.socket.read(self.READ_NUM_BYTES, timeout)
  File "/home/marshjo/.local/lib/python3.8/site-packages/httpcore/_backends/sync.py", line 62, in read
    return self.sock.recv(n)
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/marshjo/.local/lib/python3.8/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
httpcore._exceptions.ReadTimeout: The read operation timed out
```

### Environment

- OS: WSL2 Ubuntu 20.02
- Python version: 3.8
- HTTPX version: 0.13.3
- Async environment: N/A
- HTTP proxy: no
- Custom certificates: no

**Comment by florimondmanca** [comment] 2020-06-20 07:02
Hey,

What you’re seeing here is HTTPX’s “strict timeouts everywhere by default” policy, which Requests doesn’t have. There’s a 5s timeout on socket read operations by default to prevent unknowingly blocking forever. You may want to tweak it up until to something appropriate for your use case, or disable it altogether if you’re confident enough.

The docs are here: https://www.python-httpx.org/advanced/#fine-tuning-the-configuration

Going to close this for now since this is expected behavior, if you’re having trouble configuring timeouts please prefer coming by the chat. :)

**Closed by florimondmanca** 2020-06-20 07:02 UTC
Labels: question, requests-compat
