### ISSUE TITLE
Got an "Attempted to acquire an already held Lock" error when request is quickly cancelled by a small timeout in parallel async tasks

### ISSUE THREAD

**Issue by lukesolo** [encode/httpx#1885] opened 2021-10-05 07:23 UTC
I always get an "Attempted to acquire an already held Lock" error when request is quickly cancelled by a small timeout in parallel async tasks.
httpx version is 0.19.0
python version is 3.9.4
OS: Ubuntu 20.04
Here is the code to reproduce that error.

```python
import asyncio

import httpx


async def do_work(client):
    for _ in range(2):
        try:
            await asyncio.wait_for(client.get('https://example.com'), timeout=0.0001)
            print(f'{asyncio.current_task().get_name()} OK')
        except asyncio.TimeoutError:
            print(f'{asyncio.current_task().get_name()} asyncio.TimeoutError')


async def run():
    async with httpx.AsyncClient() as client:
        await asyncio.gather(*(do_work(client) for _ in range(2)))


asyncio.run(run())
```

And here the output I get:
```
Task-3 asyncio.TimeoutError
Task-2 asyncio.TimeoutError
Task-2 asyncio.TimeoutError
Traceback (most recent call last):
  File "/home/lukesolo/dev/httpx-error/src/min_reproduce.py", line 20, in <module>
    asyncio.run(run())
  File "/home/lukesolo/.pyenv/versions/3.9.4/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/lukesolo/.pyenv/versions/3.9.4/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/lukesolo/dev/httpx-error/src/min_reproduce.py", line 17, in run
    await asyncio.gather(*(do_work(client) for _ in range(2)))
  File "/home/lukesolo/dev/httpx-error/src/min_reproduce.py", line 9, in do_work
    await asyncio.wait_for(client.get('https://example.com'), timeout=0.0001)
  File "/home/lukesolo/.pyenv/versions/3.9.4/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
    return fut.result()
  File "/home/lukesolo/dev/httpx-error/.venv/lib/python3.9/site-packages/httpx/_client.py", line 1740, in get
    return await self.request(
  File "/home/lukesolo/dev/httpx-error/.venv/lib/python3.9/site-packages/httpx/_client.py", line 1494, in request
    response = await self.send(
  File "/home/lukesolo/dev/httpx-error/.venv/lib/python3.9/site-packages/httpx/_client.py", line 1586, in send
    response = await self._send_handling_auth(
  File "/home/lukesolo/dev/httpx-error/.venv/lib/python3.9/site-packages/httpx/_client.py", line 1616, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/home/lukesolo/dev/httpx-error/.venv/lib/python3.9/site-packages/httpx/_client.py", line 1655, in _send_handling_redirects
    response = await self._send_single_request(request, timeout)
  File "/home/lukesolo/dev/httpx-error/.venv/lib/python3.9/site-packages/httpx/_client.py", line 1699, in _send_single_request
    ) = await transport.handle_async_request(
  File "/home/lukesolo/dev/httpx-error/.venv/lib/python3.9/site-packages/httpx/_transports/default.py", line 281, in handle_async_request
    ) = await self._pool.handle_async_request(
  File "/home/lukesolo/dev/httpx-error/.venv/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 219, in handle_async_request
    async with self._connection_acquiry_lock:
  File "/home/lukesolo/dev/httpx-error/.venv/lib/python3.9/site-packages/httpcore/_backends/base.py", line 76, in __aenter__
    await self.acquire()
  File "/home/lukesolo/dev/httpx-error/.venv/lib/python3.9/site-packages/httpcore/_backends/anyio.py", line 104, in acquire
    await self._lock.acquire()
  File "/home/lukesolo/dev/httpx-error/.venv/lib/python3.9/site-packages/anyio/_core/_synchronization.py", line 119, in acquire
    self.acquire_nowait()
  File "/home/lukesolo/dev/httpx-error/.venv/lib/python3.9/site-packages/anyio/_core/_synchronization.py", line 146, in acquire_nowait
    raise RuntimeError('Attempted to acquire an already held Lock')
RuntimeError: Attempted to acquire an already held Lock
```

**Comment by lukesolo** [comment] 2021-10-05 07:52
If I try to send a new request after the error, it freezes indefinitely.
```
        try:
            await asyncio.wait_for(client.get('https://example.com'), timeout=0.0001)
            print(f'{asyncio.current_task().get_name()} OK')
        except asyncio.TimeoutError:
            print(f'{asyncio.current_task().get_name()} asyncio.TimeoutError')
        except RuntimeError as e:
            print(f'{asyncio.current_task().get_name()} {e}')
            resp = await client.get('https://example.com')
            print(resp.status_code)
```

**Comment by lukesolo** [comment] 2021-10-05 08:23
Downgrading to httpx==0.17.1 helps with that problem.

**Comment by tomchristie** [comment] 2021-12-16 12:55
Closing this since this code is entirely different under the latest `httpcore` version.

**Closed by tomchristie** 2021-12-16 12:55 UTC

**Comment by mscheifer** [comment] 2022-03-17 00:43
For posterity for people on older httpx / httpcore versions. I'm 99% sure this is caused by https://github.com/agronholm/anyio/issues/387 and the fix is just to upgrade your anyio version. We were seeing a similar issue and going from anyio 3.3 to 3.5 addressed it. 
- httpx 0.18.2
- httpcore 0.13.6.
