### ISSUE TITLE
RFE: please provide update for `rfc3986` 2.0.0

### ISSUE THREAD

**Issue by kloczek** [encode/httpx#2274] opened 2022-06-20 14:30 UTC
https://github.com/encode/httpx/blob/344e01e98ae528332960d34c3eca98f5472eeabf/setup.py#L58-L61

**Comment by tomchristie** [comment] 2022-06-20 14:36
Duplicate of #2169

**Closed by tomchristie** 2022-06-20 14:36 UTC

**Comment by kloczek** [comment] 2022-06-20 14:39
Sorry lost track of that tickes 😞
