### ISSUE TITLE
SSL + NordVPN Proxy 

### ISSUE THREAD

**Issue by kkm** [encode/httpx#2632] opened 2023-03-23 03:14 UTC
proxy.py:
```
import httpx
proxy = httpx.Proxy(f"https://user:password@al30.nordvpn.com:89")
proxies = {
    "http://": proxy,
    "https://": proxy,
}
client = httpx.Client(proxies=proxies)
response = client.get("https://www.example.com")
print(response.text)
client.close()
```

output from the error:
```

$python proxy.py 
Traceback (most recent call last):
  File "/home/kkm/.local/lib/python3.8/site-packages/httpx/_exceptions.py", line 339, in map_exceptions
    yield
  File "/home/kkm/.local/lib/python3.8/site-packages/httpx/_client.py", line 854, in _send_single_request
    (status_code, headers, stream, ext) = transport.request(
  File "/home/kkm/.local/lib/python3.8/site-packages/httpcore/_sync/http_proxy.py", line 124, in request
    return self._tunnel_request(
  File "/home/kkm/.local/lib/python3.8/site-packages/httpcore/_sync/http_proxy.py", line 232, in _tunnel_request
    proxy_connection.start_tls(host, timeout)
  File "/home/kkm/.local/lib/python3.8/site-packages/httpcore/_sync/connection.py", line 161, in start_tls
    self.socket = self.connection.start_tls(hostname, timeout)
  File "/home/kkm/.local/lib/python3.8/site-packages/httpcore/_sync/http11.py", line 87, in start_tls
    self.socket = self.socket.start_tls(hostname, self.ssl_context, timeout)
  File "/home/kkm/.local/lib/python3.8/site-packages/httpcore/_backends/sync.py", line 49, in start_tls
    wrapped = ssl_context.wrap_socket(
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/kkm/.local/lib/python3.8/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
httpcore.ConnectError: [SSL: UNEXPECTED_MESSAGE] unexpected message (_ssl.c:1131)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "proxy.py", line 18, in <module>
    response = client.get("https://www.example.com")
  File "/home/kkm/.local/lib/python3.8/site-packages/httpx/_client.py", line 900, in get
    return self.request(
  File "/home/kkm/.local/lib/python3.8/site-packages/httpx/_client.py", line 721, in request
    return self.send(
  File "/home/kkm/.local/lib/python3.8/site-packages/httpx/_client.py", line 753, in send
    response = self._send_handling_auth(
  File "/home/kkm/.local/lib/python3.8/site-packages/httpx/_client.py", line 791, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/home/kkm/.local/lib/python3.8/site-packages/httpx/_client.py", line 823, in _send_handling_redirects
    response = self._send_single_request(request, timeout)
  File "/home/kkm/.local/lib/python3.8/site-packages/httpx/_client.py", line 854, in _send_single_request
    (status_code, headers, stream, ext) = transport.request(
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/kkm/.local/lib/python3.8/site-packages/httpx/_exceptions.py", line 356, in map_exceptions
    raise mapped_exc(message, **kwargs) from exc  # type: ignore
httpx.ConnectError: [SSL: UNEXPECTED_MESSAGE] unexpected message (_ssl.c:1131)

```

Linux: Ubuntu 20.04 focal 
Python 3.8.10

I am not sure if I am wrong with my code or SSL bug?

**Comment by byehack** [comment] 2023-03-28 18:36
same as https://github.com/encode/httpx/issues/1373
try https://github.com/encode/httpx/issues/1434#issuecomment-979193104

**Comment by tomchristie** [comment] 2023-04-05 13:38
duplicate of #1434.

**Closed by tomchristie** 2023-04-05 13:38 UTC
