### ISSUE TITLE
Incompatibility: param that is None is still included 

### ISSUE THREAD

**Issue by louwers** [encode/httpx#1261] opened 2020-09-04 21:33 UTC
### Checklist

- [X] The bug is reproducible against the latest release and/or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

Your docs state 

> HTTPX aims to be compatible with the requests API wherever possible.

so I am reporting this as a bug. When `None` is one of the parameter values (provided with `params`), it is still included. While this is not the case for requests.

### To reproduce

```
>>> import requests
>>> requests.get("https://httpbin.org/get", params={"foo": "bar", "baz": None}).json()["url"]
'https://httpbin.org/get?foo=bar'
```

versus

```
>>> import httpx
>>> import asyncio
>>>
>>> async def get_httpbin():
>>>     async with httpx.AsyncClient() as client:
>>>         r = await client.get("https://httpbin.org/get", params={"foo": "bar", "baz": None})
>>>         print(r.json()["url"])
>>> asyncio.run(get_httpbin())
https://httpbin.org/get?foo=bar&baz=
```

### Expected behavior

A request to `https://httpbin.org/get?foo=bar` is made.

### Actual behavior

A request to `https://httpbin.org/get?foo=bar&baz=` is made.

**Comment by florimondmanca** [comment] 2020-09-04 22:09
Felt like this had been discussed before, and surely, it has:

This is essentially a duplicate of #154

At the time was closed by #174 in the name of adhering to strict typing, as well as "Requests isn't doing the best thing there" — hence why we're differing in API here.

As a note: `None` values _could_ have been reserved to mean "include a query param without `=` (such as `{"q": None}` -> `q`, instead of `q=` for `{"q": ""}`), a use case that Requests would want to address but can't due to the existing behavior you're asking about here - see psf/requests#2651. Adding this was deemed as an unecessary feature though (for such esoteric cases it's probably okay to just build the query string manually).

So, closing as a duplicate — thanks!

**Closed** 2020-09-04 22:09 UTC
Labels: duplicate
