### ISSUE TITLE
URL cached incorrectly

### ISSUE THREAD

**Issue by abersheeran** [encode/httpx#1472] opened 2021-02-17 14:10 UTC
### Checklist

- [x] The bug is reproducible against the latest release and/or `master`.
- [x] There are no similar issues or pull requests to fix it yet.

### To reproduce

```python
async def asgi(scope, receive, send):
    print(scope)
    await send(
        {
            "type": "http.response.start",
            "status": 200,
            "headers": [],
        }
    )
    await send({"type": "http.response.body", "body": ""})


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(asgi, interface="asgi3", port=65432)
```

```python
import httpx

base_url = "http://127.0.0.1:65432/"
client = httpx.Client(proxies=None)
client.post(base_url + "a").raise_for_status()
client.post(base_url + "b").raise_for_status()
```

### Actual behavior

In the first request, everything was normal, but in the second request, there was an error in the URL! `http://127.0.0.1:65432` was again incorrectly appended to the URL.

### Debugging material

Server output:

```
{'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 65432), 'client': ('127.0.0.1', 7846), 'scheme': 'http', 'method': 'POST', 'root_path': '', 'path': '/a', 'raw_path': b'/a', 'query_string': b'', 'headers': [(b'host', b'127.0.0.1:65432'), (b'content-length', b'0'), (b'accept', b'*/*'), (b'accept-encoding', b'gzip, deflate'), (b'connection', b'keep-alive'), (b'user-agent', b'python-httpx/0.16.1')]}
INFO:     127.0.0.1:7846 - "POST /a HTTP/1.1" 200 OK
{'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 65432), 'client': ('127.0.0.1', 7846), 'scheme': 'http', 'method': 'POST', 'root_path': '', 'path': 'http://127.0.0.1:65432/b', 'raw_path': b'http://127.0.0.1:65432/b', 'query_string': b'', 'headers': [(b'host', b'127.0.0.1:65432'), (b'content-length', b'0'), (b'accept', b'*/*'), (b'accept-encoding', b'gzip, deflate'), (b'connection', b'keep-alive'), (b'user-agent', b'python-httpx/0.16.1')]}
INFO:     127.0.0.1:7846 - "POST http%3A//127.0.0.1%3A65432/b HTTP/1.1" 200 OK
```

### Environment

- OS:  Windows10
- Python version:  3.7.4
- HTTPX version:  0.16.1
- HTTP proxy:  no
- Custom certificates:  no

**Comment by euri10** [comment] 2021-02-17 14:30
I'll let the pro answer but I think if you want to interact with your app just just have to pass the base_url to the client:
```
import httpx

base_url = "http://127.0.0.1:65432/"
client = httpx.Client(proxies=None, base_url=base_url)
client.post("a").raise_for_status()
client.post("b").raise_for_status()
```

```
{'type': 'lifespan', 'asgi': {'version': '3.0', 'spec_version': '2.0'}}
{'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 65432), 'client': ('127.0.0.1', 56836), 'scheme': 'http', 'method': 'POST', 'root_path': '', 'path': '/a', 'raw_path': b'/a', 'query_string': b'', 'headers': [(b'host', b'127.0.0.1:65432'), (b'content-length', b'0'), (b'accept', b'*/*'), (b'accept-encoding', b'gzip, deflate'), (b'connection', b'keep-alive'), (b'user-agent', b'python-httpx/0.16.1')]}
INFO:     127.0.0.1:56836 - "POST /a HTTP/1.1" 200 OK
{'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 65432), 'client': ('127.0.0.1', 56836), 'scheme': 'http', 'method': 'POST', 'root_path': '', 'path': '/b', 'raw_path': b'/b', 'query_string': b'', 'headers': [(b'host', b'127.0.0.1:65432'), (b'content-length', b'0'), (b'accept', b'*/*'), (b'accept-encoding', b'gzip, deflate'), (b'connection', b'keep-alive'), (b'user-agent', b'python-httpx/0.16.1')]}
INFO:     127.0.0.1:56836 - "POST /b HTTP/1.1" 200 OK
```

**Comment by abersheeran** [comment] 2021-02-17 14:37
![image](https://user-images.githubusercontent.com/25364828/108219299-8feecd80-7170-11eb-8fd7-cbd2da7aca45.png)

I tried your code, but the result is still wrong.

**Comment by euri10** [comment] 2021-02-17 15:10
> I tried your code, but the result is still wrong.

maybe a diff linux / windows, looks weird same code produces different results

**Comment by florimondmanca** [comment] 2021-02-17 17:26
:wave:

Indeed, seems to be a Windows-specific issue. I'm not able to replicate on macOS either:

```python
import httpx

client = httpx.Client()
client.post("http://127.0.0.1:8000/a")
client.post("http://127.0.0.1:8000/b")
```

Uvicorn:

```console
INFO:     127.0.0.1:54437 - "POST /a HTTP/1.1" 200 OK
INFO:     127.0.0.1:54437 - "POST /b HTTP/1.1" 200 OK
```

@abersheeran Can you also replicate when using a raw transport? If so, we'll know the issue is in HTTPCore; otherwise, the issue is somewhere in HTTPX. :-)

```python
import httpcore

origin = (b"http", b"127.0.0.1", 8000)

with httpcore.SyncConnectionPool() as http:
    status_code, headers, stream, ext = http.request(b"GET", (*origin, b"/a"), headers=[(b"host", b"localhost")])
    stream.close()

    status_code, headers, stream, ext = http.request(b"GET", (*origin, b"/b"), headers=[(b"host", b"localhost")])
    stream.close()
```

**Comment by abersheeran** [comment] 2021-02-18 00:09
![image](https://user-images.githubusercontent.com/25364828/108284583-79706280-71c0-11eb-8e3e-49653ecaa5fb.png)

**Comment by euri10** [comment] 2021-02-18 08:15
I just popped of a win10 machine, ran the code and got no issue
```
import httpx

base_url = "http://127.0.0.1:65432/"
client = httpx.Client(proxies=None, base_url=base_url)
client.post("a").raise_for_status()
client.post("b").raise_for_status()
```

```
C:\Users\benoi\PycharmProjects\uvicorn\venv38\Scripts\python.exe C:/Users/benoi/PycharmProjects/uvicorn/1472.py
{'type': 'lifespan', 'asgi': {'version': '3.0', 'spec_version': '2.0'}}
INFO:     Started server process [10104]
INFO:     Waiting for application startup.
INFO:     ASGI 'lifespan' protocol appears unsupported.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:65432 (Press CTRL+C to quit)
INFO:     going to await shutdown
{'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 65432), 'client': ('127.0.0.1', 49869), 'scheme': 'http', 'method': 'POST', 'root_path': '', 'path': '/a', 'raw_path': b'/a', 'query_string': b'', 'headers': [(b'host', b'127.0.0.1:65432'), (b'content-length', b'0'), (b'accept', b'*/*'), (b'accept-encoding', b'gzip, deflate'), (b'connection', b'keep-alive'), (b'user-agent', b'python-httpx/0.16.1')]}
INFO:     127.0.0.1:49869 - "POST /a HTTP/1.1" 200 OK
{'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 65432), 'client': ('127.0.0.1', 49869), 'scheme': 'http', 'method': 'POST', 'root_path': '', 'path': '/b', 'raw_path': b'/b', 'query_string': b'', 'headers': [(b'host', b'127.0.0.1:65432'), (b'content-length', b'0'), (b'accept', b'*/*'), (b'accept-encoding', b'gzip, deflate'), (b'connection', b'keep-alive'), (b'user-agent', b'python-httpx/0.16.1')]}
INFO:     127.0.0.1:49869 - "POST /b HTTP/1.1" 200 OK
```

**Comment by abersheeran** [comment] 2021-02-18 08:24
@euri10 This is really confusing. Maybe it's not a system problem?

**Comment by j178** [comment] 2021-02-18 08:32
@abersheeran Hi, can you try it with `requests`?
```py
import requests

base_url = "http://127.0.0.1:65432/"
session = requests.Session()
session.trust_env = False
session.post(base_url + "a")
session.post(base_url + "b")
```

**Comment by abersheeran** [comment] 2021-02-18 08:40
![image](https://user-images.githubusercontent.com/25364828/108328705-e0653a00-7207-11eb-87b8-7db97d7441f2.png)

everything is normal.

**Comment by florimondmanca** [comment] 2021-02-18 14:59
Very strange affair. @abersheeran, mind sharing the result of running your script with trace logging enabled?

```console
$ HTTPX_LOG_LEVEL=trace python script.py
```

(Not sure how to pass an env variable on Windows, you'd need to adapt this^.)

**Comment by abersheeran** [comment] 2021-02-18 15:38
```
TRACE [2021-02-18 23:37:42] httpx._config - load_ssl_context verify=True cert=None trust_env=True http2=False
TRACE [2021-02-18 23:37:42] httpx._config - load_verify_locations cafile=C:\Users\AberS\Desktop\t\.venv\lib\site-packages\certifi\cacert.pem
TRACE [2021-02-18 23:37:42] httpx._config - load_ssl_context verify=True cert=None trust_env=True http2=False
TRACE [2021-02-18 23:37:42] httpx._config - load_verify_locations cafile=C:\Users\AberS\Desktop\t\.venv\lib\site-packages\certifi\cacert.pem
TRACE [2021-02-18 23:37:42] httpcore._sync.http_proxy - forward_request proxy_origin=(b'http', b'127.0.0.1', 3128) proxy_headers=[] method=b'POST' url=(b'http', b'127.0.0.1', 65432, b'/a')
TRACE [2021-02-18 23:37:42] httpcore._sync.connection_pool - adding connection to pool=<SyncHTTPConnection http_version=UNKNOWN state=0>
TRACE [2021-02-18 23:37:42] httpcore._sync.connection - open_socket origin=(b'http', b'127.0.0.1', 3128) timeout={'connect': 5.0, 'read': 5.0, 'write': 5.0, 'pool': 5.0}
TRACE [2021-02-18 23:37:42] httpcore._sync.connection - create_connection socket=<httpcore._backends.sync.SyncSocketStream object at 0x0000021E7F208FC8> http_version='HTTP/1.1'
TRACE [2021-02-18 23:37:42] httpcore._sync.connection - connection.request 
method=b'POST' url=(b'http', b'127.0.0.1', 3128, b'http://127.0.0.1:65432/a') headers=[(b'Host', b'127.0.0.1:65432'), (b'Content-Length', b'0'), (b'Accept', b'*/*'), (b'Accept-Encoding', b'gzip, deflate'), (b'Connection', b'keep-alive'), (b'User-Agent', b'python-httpx/0.16.1')]
TRACE [2021-02-18 23:37:42] httpcore._sync.http11 - send_request method=b'POST' url=(b'http', b'127.0.0.1', 3128, b'http://127.0.0.1:65432/a') headers=[(b'Host', b'127.0.0.1:65432'), (b'Content-Length', b'0'), (b'Accept', b'*/*'), (b'Accept-Encoding', b'gzip, deflate'), (b'Connection', b'keep-alive'), (b'User-Agent', b'python-httpx/0.16.1')]
TRACE [2021-02-18 23:37:42] httpcore._sync.http11 - send_data=Data(<0 bytes>)
DEBUG [2021-02-18 23:37:42] httpx._client - HTTP Request: POST http://127.0.0.1:65432/a "HTTP/1.1 200 OK"
TRACE [2021-02-18 23:37:42] httpcore._sync.http11 - receive_event=EndOfMessage(headers=<Headers([])>)
TRACE [2021-02-18 23:37:42] httpcore._sync.http11 - response_closed our_state=DONE their_state=DONE
TRACE [2021-02-18 23:37:42] httpcore._sync.http_proxy - forward_request proxy_origin=(b'http', b'127.0.0.1', 3128) proxy_headers=[] method=b'POST' url=(b'http', b'127.0.0.1', 65432, b'/b')
TRACE [2021-02-18 23:37:42] httpcore._sync.connection_pool - reusing idle http11 connection=<SyncHTTPConnection http_version=HTTP/1.1 state=4>        
TRACE [2021-02-18 23:37:42] httpcore._sync.connection - connection.request 
method=b'POST' url=(b'http', b'127.0.0.1', 3128, b'http://127.0.0.1:65432/b') headers=[(b'Host', b'127.0.0.1:65432'), (b'Content-Length', b'0'), (b'Accept', b'*/*'), (b'Accept-Encoding', b'gzip, deflate'), (b'Connection', b'keep-alive'), (b'User-Agent', b'python-httpx/0.16.1')]
TRACE [2021-02-18 23:37:42] httpcore._sync.http11 - send_request method=b'POST' url=(b'http', b'127.0.0.1', 3128, b'http://127.0.0.1:65432/b') headers=[(b'Host', b'127.0.0.1:65432'), (b'Content-Length', b'0'), (b'Accept', b'*/*'), (b'Accept-Encoding', b'gzip, deflate'), (b'Connection', b'keep-alive'), (b'User-Agent', b'python-httpx/0.16.1')]
TRACE [2021-02-18 23:37:42] httpcore._sync.http11 - send_data=Data(<0 bytes>)
DEBUG [2021-02-18 23:37:42] httpx._client - HTTP Request: POST http://127.0.0.1:65432/b "HTTP/1.1 200 OK"
TRACE [2021-02-18 23:37:42] httpcore._sync.http11 - receive_event=EndOfMessage(headers=<Headers([])>)
TRACE [2021-02-18 23:37:42] httpcore._sync.http11 - response_closed our_state=DONE their_state=DONE
TRACE [2021-02-18 23:37:42] httpcore._sync.connection_pool - removing connection from pool=<SyncHTTPConnection http_version=HTTP/1.1 state=4>
```

**Comment by tomchristie** [comment] 2021-02-18 15:38
So... since this hasn't yet been reproduced by anyone, one possibility is that either your httpx or your uvicorn source isn't in a pristine state locally (eg. been edited for debugging or something) and that's what's causing the issue.

Some things that would be worth trying would be:

* Isolating if the issue you're seeing is client side or server side. Try running gunicorn instead of uvicorn, and sending the requests to that - are you still seeing the same error?
* Make sure to set up a completely clean virtualenv, and ensure that you're running within that.

**Comment by tomchristie** [comment] 2021-02-18 15:40
It might also be a good idea to run with `httpx.Client(trust_env=False)` since that'll replicate more consistently.

**Comment by florimondmanca** [comment] 2021-02-18 16:02
@abersheeran From the log output you shared, you'll note that your HTTP client _is_ actually using a proxy (see those "forward proxy …" log lines). I assume it comes from the environment (eg picking up `HTTP_PROXY`). Per Tom's recommendation you might want to try `trust_env=False` (`proxies=None` has no effect). If the issue doesn't reproduce without a proxy, and your local state is pristine, then we can look further into proxy code if need be.

**Comment by abersheeran** [comment] 2021-02-19 02:00
Yes, I just tried to remove the proxy. Found that everything is normal.

**Comment by tomchristie** [comment] 2021-02-19 13:06
Interesting. Perhaps you could see if you're able to replicate the issue using a *different* proxy.
Eg. install this https://pypi.org/project/proxy.py/ and use `trust_env=False, proxies="..."` to point at it directly.

That'd help us figure out if the issue is with the client or the proxy, and would also give us a better chance of being able to replicate the issue ourselves.

**Comment by abersheeran** [comment] 2021-02-20 02:53
I will try it when I go home at night.

**Comment by tomchristie** [comment] 2021-03-01 13:53
For now I'm going to close this off as unconfirmed. (Because we don't know if the issue was on the side of the proxy or on the side of httpx, and we've not had enough info for anyone else to reproduce this.)

**Closed by tomchristie** 2021-03-01 13:53 UTC
Labels: needs confirmation
