### ISSUE TITLE
http2 wait_for_event can not exit loop

### ISSUE THREAD

**Issue by kofboy** [encode/httpx#860] opened 2020-03-12 16:46 UTC
http2.py

    async def wait_for_event(self, stream_id: int, timeout: Timeout) -> h2.events.Event:
        """
        Returns the next event for a given stream.

        If no events are available yet, then waits on the network until
        an event is available.
        """
        while not self.events[stream_id]:
            await self.receive_events(timeout) #**here can not exit loop when socket read empty data and no event append to list**
        return self.events[stream_id].pop(0)

**Comment by florimondmanca** [comment] 2020-03-13 20:34
Hi @kofboy 

We're going to need a bit more context about this. :-)

Can you share your use case (i.e. what are you trying to achieve?) and ideally a minimal reproduction snippet so we can further explore what might be wrong?

Thanks

**Comment by florimondmanca** [comment] 2020-03-25 11:18
Closing due to lack of info, feel free to reach out here on on the [chat](https://gitter.im/encode/community) if this is still a problem!

**Closed by florimondmanca** 2020-03-25 11:18 UTC
Labels: http/2, need-info
